// 🐾 The special question banks inside "Animal Kingdom" (see animals.js for how they're mixed).
// Each one is a plain list of questions, like Space Explorer. A "guide" from Rufus's game presents them:
//   🐍 Snake Spotter   - the snakes from the level "Snakes on the Moon"
//   🦊 Rufus's Fox Facts
//   🦖 Fiery's Dino Dig
//   🌍 Amazing Animals - records and surprises from all over the world
// level: 1 = easy, 2 = medium, 3 = hard. Facts must be true; when scientists aren't sure, say "scientists think".

import { bankTopic } from "../kit.js";

export const snakes = bankTopic({
  id: "snakes",
  title: "Snake Spotter",
  emoji: "🐍",
  eyebrow: "Snake Spotter",
  guide: { who: "viper", place: "The Moon" },
  questions: [
    { q: "How do snakes smell things?", a: "With their flicking tongues", wrong: ["With their tails", "With their scales", "Snakes can't smell"], level: 1,
      fact: "A snake flicks its forked tongue to catch smells from the air, then wipes them onto little pads in its mouth that pass them up to a special smelling spot." },
    { q: "What does a snake do when its skin gets too tight?", a: "Sheds it and has a new one underneath", wrong: ["Stops eating forever", "Turns into a lizard", "Asks for a bigger one"], level: 1, who: "milksnake",
      fact: "Snakes shed their whole skin, often in one long piece, even the clear scales over their eyes!" },
    { q: "Snakes belong to which animal group?", a: "Reptiles", wrong: ["Amphibians", "Mammals", "Insects"], level: 1, who: "kingcobra",
      fact: "Snakes are reptiles, like lizards, turtles and crocodiles. They have dry, scaly skin." },
    { q: "How does a snake eat its food?", a: "It swallows it whole", wrong: ["It chews it slowly", "It nibbles like a rabbit", "It cuts it up first"], level: 1,
      fact: "Snakes can't chew. Their super-stretchy jaws let them swallow food that's bigger than their own head!" },
    { q: "Which snake shakes its tail to make a warning sound?", a: "Rattlesnake", wrong: ["King cobra", "Anaconda", "Milk snake"], level: 1,
      fact: "A rattle is made of keratin, like your fingernails. The snake gets a new piece every time it sheds." },
    { q: "Which snake spreads a wide hood around its neck?", a: "Cobra", wrong: ["Python", "Rattlesnake", "Anaconda"], level: 1,
      fact: "A cobra stretches out long ribs in its neck to make its famous hood and look extra big." },
    { q: "How do snakes move without legs?", a: "They push with the scales on their belly", wrong: ["They roll like a ball", "They hop on their tail", "They use tiny hidden feet"], level: 1,
      fact: "Belly scales grip the ground as the snake wiggles. Pythons and boas even have tiny leftover hip spurs from long-ago legs!" },
    { q: "In Adventures of Rufus, where do the king cobras, rattlesnakes and milk snakes live?", a: "On the Moon", wrong: ["In the Library", "In Candy Kingdom", "In the School Gym"], level: 1, who: "kingcobra",
      fact: "It's the level Snakes on the Moon! Jump carefully, Rufus." },
    { q: "What is the longest snake in the world?", a: "Reticulated python", wrong: ["King cobra", "Black mamba", "Garter snake"], level: 2, who: "viper",
      fact: "Reticulated pythons can grow longer than 6 metres. That's longer than a car!" },
    { q: "What is the heaviest snake in the world?", a: "Green anaconda", wrong: ["Reticulated python", "Rattlesnake", "Corn snake"], level: 2,
      fact: "Green anacondas live in the rivers and swamps of South America and can weigh more than a grown-up person." },
    { q: "What does a king cobra mostly eat?", a: "Other snakes", wrong: ["Fruit", "Grass", "Seaweed"], level: 2, who: "kingcobra",
      fact: "King cobras are the longest venomous snakes in the world, and their favourite food is other snakes!" },
    { q: "Which harmless snake is a copycat, with red, black and yellow bands that look like a coral snake's?", a: "Milk snake", wrong: ["King cobra", "Rattlesnake", "Black mamba"], level: 2,
      fact: "Milk snakes are harmless, but scientists think their bright bands look enough like a coral snake's that hungry animals leave them alone." },
    { q: "Snakes don't have eyelids. What protects their eyes?", a: "A clear, see-through scale", wrong: ["Thick eyebrows", "Their tongue", "Fluffy fur"], level: 2, who: "milksnake",
      fact: "Each eye has a clear scale over it, like built-in goggles. That's why snakes never blink!" },
    { q: "Which snake plays dead when it's scared?", a: "Hognose snake", wrong: ["King cobra", "Anaconda", "Black mamba"], level: 2,
      fact: "A scared hognose snake flops onto its back, opens its mouth and lies still. What an actor!" },
    { q: "Which country is famous for having no wild snakes?", a: "Ireland", wrong: ["Australia", "India", "Brazil"], level: 2, who: "milksnake",
      fact: "Ireland has no native snakes. Scientists think the Ice Age kept them away, and then the sea stopped them getting there." },
    { q: "How do rattlesnakes find warm animals in the dark?", a: "They sense body heat", wrong: ["They use a torch", "Their eyes glow", "They can't hunt at night"], level: 2, who: "rattlesnake",
      fact: "Rattlesnakes are pit vipers. Little heat-sensing pits on their faces let them 'see' warm animals in the dark." },
    { q: "How does a mother python look after her eggs?", a: "She coils around them to keep them warm", wrong: ["She buries them and leaves", "The dad carries them", "She sits on them like a hen"], level: 2,
      fact: "A python mum wraps around her eggs. Some, like Burmese python mums, can even shiver to warm them up!" },
    { q: "What do egg-eating snakes do with the eggshell?", a: "Crack it inside and spit it out", wrong: ["Keep it as a hat", "Eat it last", "Bury it"], level: 2,
      fact: "Egg-eating snakes swallow a bird's egg whole, crack it with special bones in their throat, and spit out the shell." },
    { q: "Which snake can glide from tree to tree?", a: "Paradise tree snake", wrong: ["Green anaconda", "Milk snake", "Sidewinder"], level: 3,
      fact: "Paradise tree snakes flatten their bodies like a ribbon and glide through the rainforests of Asia." },
    { q: "What is the smallest snake in the world?", a: "Barbados threadsnake", wrong: ["Garter snake", "Corn snake", "Grass snake"], level: 3,
      fact: "The Barbados threadsnake is only about 10 cm long, small enough to curl up on a coin!" },
    { q: "Which shy land snake has the most powerful venom?", a: "Inland taipan", wrong: ["Milk snake", "Corn snake", "Garter snake"], level: 3, who: "spitcobra",
      fact: "The inland taipan lives in the hot, dry outback of central Australia. It's very shy and almost never meets people." },
    { q: "About how many kinds of snake are there?", a: "About 4,000", wrong: ["About 40", "About 400", "About 4 million"], level: 3, who: "kingcobra",
      fact: "Scientists know about 4,000 kinds of snake, living on every continent except Antarctica." },
    { q: "Which snake moves sideways across hot desert sand?", a: "Sidewinder", wrong: ["Sea snake", "King cobra", "Anaconda"], level: 3,
      fact: "Sidewinders are little rattlesnakes. Moving sideways means only small bits of them touch the hot sand." },
    { q: "Where do sea snakes live?", a: "In warm oceans", wrong: ["On snowy mountains", "Only in deserts", "In caves"], level: 3, who: "milksnake",
      fact: "Sea snakes swim with flat, paddle-shaped tails and come up to the surface to breathe air." },
    { q: "Why do spitting cobras spit?", a: "To protect themselves from danger", wrong: ["To catch flies", "To clean their teeth", "To say hello"], level: 3, who: "spitcobra",
      fact: "A spitting cobra sprays a stinging mist toward whatever is bothering it, then slithers away while the other animal is busy blinking." },
  ],
});

export const foxes = bankTopic({
  id: "foxes",
  title: "Rufus's Fox Facts",
  emoji: "🦊",
  eyebrow: "Rufus's Fox Facts",
  guide: { who: "rufus", place: "The fox den" },
  questions: [
    { q: "What is a mother fox called?", a: "A vixen", wrong: ["A mare", "A ewe", "A doe"], level: 1,
      fact: "A mother fox is a vixen. A dad fox is called a dog, or a tod." },
    { q: "Foxes belong to which animal family?", a: "The dog family", wrong: ["The cat family", "The bear family", "The rabbit family"], level: 1,
      fact: "Foxes are cousins of wolves and dogs. Scientists call this family the canids." },
    { q: "Which fox has giant ears to help it stay cool in the desert?", a: "Fennec fox", wrong: ["Arctic fox", "Red fox", "Gray fox"], level: 1,
      fact: "A fennec fox's ears let heat escape, and they're so good they can hear bugs moving under the sand!" },
    { q: "Which fox turns white in winter?", a: "Arctic fox", wrong: ["Fennec fox", "Red fox", "Kit fox"], level: 1,
      fact: "Most Arctic foxes turn white in winter to hide in the snow, and brown or grey in summer. A few 'blue' Arctic foxes stay dark grey all year!" },
    { q: "What is a fox's home called?", a: "A den", wrong: ["A nest", "A hive", "A stable"], level: 1,
      fact: "Foxes dig dens underground (also called earths) to raise their kits." },
    { q: "In Adventures of Rufus, who is Rufus's dad?", a: "Felix", wrong: ["Renard", "Fiery", "King Clown"], level: 1,
      fact: "Felix taught Rufus to smile, and to sing. Mostly to sing!" },
    { q: "Which fox in Adventures of Rufus is called The Grumpy One?", a: "Renard", wrong: ["Felix", "Rufus", "Marthina"], level: 1,
      fact: "Those angry eyebrows give Renard away. But even grumps have a spark!" },
    { q: "In Adventures of Rufus, which fox is The Chef?", a: "Marthina", wrong: ["Renard", "Felix", "Fiery"], level: 1,
      fact: "Marthina is The Chef. Mangia, mangia!" },
    { q: "What is a fox's bushy tail called?", a: "A brush", wrong: ["A broom", "A feather", "A mop"], level: 2,
      fact: "A fox's tail is called a brush. Foxes curl it around themselves like a blanket to sleep. Rufus's has a white tip!" },
    { q: "Which kind of fox can climb trees?", a: "Gray fox", wrong: ["Arctic fox", "Fennec fox", "Bat-eared fox"], level: 2,
      fact: "Gray foxes have strong, curved claws and can scramble up trees, which most foxes can't do!" },
    { q: "Which fox lives in more places around the world than any other?", a: "Red fox", wrong: ["Fennec fox", "Arctic fox", "Gray fox"], level: 2,
      fact: "Red foxes live in forests, fields, mountains and even big cities, all over Europe, Asia, North America, North Africa and Australia." },
    { q: "How does a fox find a mouse hiding under the snow?", a: "It listens, then leaps up and dives in nose-first", wrong: ["It digs all night", "It waits for spring", "It calls the mouse's name"], level: 2,
      fact: "Foxes have amazing hearing. This high leap and dive is called mousing!" },
    { q: "What is the smallest kind of fox?", a: "Fennec fox", wrong: ["Red fox", "Arctic fox", "Gray fox"], level: 2,
      fact: "Fennec foxes weigh about as much as a bag of sugar, about 1 kg. They're the smallest wild member of the dog family." },
    { q: "What shape are a red fox's pupils?", a: "Up-and-down slits, like a cat's", wrong: ["Round, like ours", "Star-shaped", "Square"], level: 2,
      fact: "Scientists think slit-shaped pupils help red foxes judge how far away a mouse is, and see well in both bright and dim light." },
    { q: "About how fast can a red fox run?", a: "About 50 km/h", wrong: ["About 5 km/h", "About 15 km/h", "About 200 km/h"], level: 3,
      fact: "Red foxes can sprint at about 50 km/h (30 mph). That's as fast as a car driving through town!" },
    { q: "Foxes have whiskers on their face. Where else do they have some?", a: "On their front legs", wrong: ["On their tail", "On their back", "Inside their ears"], level: 3,
      fact: "Whiskers near the wrists of their front legs help foxes feel what's around their paws, handy when sneaking up on a mouse in the dark." },
    { q: "What do foxes eat?", a: "Almost anything: mice, bugs, berries and fruit", wrong: ["Only grass", "Only fish", "Only carrots"], level: 3,
      fact: "Foxes are omnivores, which means they eat both plants and animals. City foxes even raid bins!" },
  ],
});

export const dinos = bankTopic({
  id: "dinos",
  title: "Fiery's Dino Dig",
  emoji: "🦖",
  eyebrow: "Fiery's Dino Dig",
  guide: { who: "fiery", place: "The fossil dig" },
  questions: [
    { q: "What kind of dinosaur is Fiery in Adventures of Rufus?", a: "A baby T. rex", wrong: ["A Stegosaurus", "A Triceratops", "A Brachiosaurus"], level: 1,
      fact: "Fiery has tiny arms, a big head and the biggest toothy grin in the family." },
    { q: "Which dinosaur had three horns on its face?", a: "Triceratops", wrong: ["T. rex", "Stegosaurus", "Velociraptor"], level: 1,
      fact: "Triceratops means 'three-horned face'. It also had a big bony frill around its neck." },
    { q: "Which dinosaur had big plates on its back and a spiky tail?", a: "Stegosaurus", wrong: ["Triceratops", "T. rex", "Diplodocus"], level: 1,
      fact: "The spikes on a Stegosaurus tail have a funny nickname: the thagomizer!" },
    { q: "Which animals alive today are actually dinosaurs?", a: "Birds", wrong: ["Cats", "Frogs", "Sharks"], level: 1,
      fact: "Birds are living dinosaurs! A chicken is a distant cousin of T. rex." },
    { q: "Did baby dinosaurs hatch from eggs?", a: "Yes, all of them", wrong: ["No, they were born like puppies", "Only the flying ones", "Only T. rex"], level: 1,
      fact: "Scientists think every dinosaur hatched from an egg. Some dinosaur eggs were as big as a football!" },
    { q: "What do we call scientists who study fossils?", a: "Paleontologists", wrong: ["Astronauts", "Zookeepers", "Geographers"], level: 2,
      fact: "Paleontologists dig up fossils and work out how long-ago animals lived." },
    { q: "About how long ago did the last giant dinosaurs disappear?", a: "66 million years ago", wrong: ["6,000 years ago", "100 years ago", "1 billion years ago"], level: 2,
      fact: "Scientists think a giant asteroid hit Earth 66 million years ago. The bird-dinosaurs made it through!" },
    { q: "Which dinosaur had a heavy club at the end of its tail?", a: "Ankylosaurus", wrong: ["Diplodocus", "T. rex", "Triceratops"], level: 2,
      fact: "Ankylosaurus was covered in bony armour, like a walking tank. Scientists think it swung its tail club in shoving contests with other ankylosaurs, and maybe to keep hungry T. rex away." },
    { q: "What does the name Tyrannosaurus rex mean?", a: "Tyrant lizard king", wrong: ["Three-horned face", "Speedy thief", "Roof lizard"], level: 2,
      fact: "T. rex had teeth about as long as bananas!" },
    { q: "Real Velociraptors were about the size of a…", a: "Turkey", wrong: ["Bus", "Elephant", "Mouse"], level: 2,
      fact: "Real Velociraptors were turkey-sized, and they had feathers!" },
    { q: "Which flying reptile lived with the dinosaurs but was NOT a dinosaur?", a: "Pteranodon", wrong: ["Stegosaurus", "Triceratops", "Diplodocus"], level: 2,
      fact: "Pteranodon was a pterosaur, a flying cousin of the dinosaurs." },
    { q: "What is a coprolite?", a: "Fossilised poo", wrong: ["A dinosaur egg", "A sparkly rock", "A baby dinosaur"], level: 2,
      fact: "Yes, really! Coprolites can come from any ancient animal, and fossil dino poo shows scientists what dinosaurs ate." },
    { q: "Which dinosaur had front legs longer than its back legs, like a giraffe?", a: "Brachiosaurus", wrong: ["T. rex", "Stegosaurus", "Velociraptor"], level: 3,
      fact: "Scientists think Brachiosaurus held its long neck up high, like a giraffe, to reach the tallest treetops." },
    { q: "Who lived closer in time: T. rex and you, or T. rex and Stegosaurus?", a: "T. rex and you!", wrong: ["T. rex and Stegosaurus", "They all lived at the same time", "Nobody knows"], level: 3,
      fact: "Stegosaurus lived about 150 million years ago and T. rex about 66 million years ago, so T. rex is closer in time to us!" },
    { q: "Which dinosaur had a tall sail on its back and caught fish?", a: "Spinosaurus", wrong: ["Ankylosaurus", "Triceratops", "Iguanodon"], level: 3,
      fact: "Spinosaurus may have been even longer than T. rex, and scientists think it spent lots of time in rivers." },
    { q: "Mary Anning was a famous fossil hunter. About how old was she when she found her first big fossil?", a: "About 12", wrong: ["About 3", "About 50", "About 90"], level: 3,
      fact: "Around 1811, young Mary Anning and her brother found a giant sea reptile, an ichthyosaur, on the beach in Lyme Regis, England." },
    { q: "Where in the world have dinosaur fossils been found?", a: "On every continent, even Antarctica", wrong: ["Only in North America", "Only in Africa", "Only in Europe"], level: 3,
      fact: "When dinosaurs lived, Antarctica was much warmer, with forests!" },
  ],
});

export const wild = bankTopic({
  id: "wild",
  title: "Amazing Animals",
  emoji: "🌍",
  eyebrow: "Amazing animals",
  questions: [
    { q: "What is the fastest land animal?", a: "Cheetah", wrong: ["Lion", "Horse", "Kangaroo"], level: 1, emoji: "💨",
      fact: "A cheetah can sprint at about 100 km/h, but only in short bursts before it needs a rest." },
    { q: "What is the biggest animal that has ever lived?", a: "Blue whale", wrong: ["T. rex", "African elephant", "Giant squid"], level: 1, emoji: "🏆",
      fact: "Blue whales are even heavier than the biggest dinosaurs!" },
    { q: "What is the tallest animal?", a: "Giraffe", wrong: ["Elephant", "Ostrich", "Camel"], level: 1, emoji: "📏",
      fact: "Giraffes can be taller than 5 metres, and their dark tongues are about 50 cm long!" },
    { q: "Which animal sleeps hanging upside down?", a: "Bat", wrong: ["Owl", "Monkey", "Duck"], level: 1, emoji: "🌙",
      fact: "Bats hang upside down so they can just let go and fly away." },
    { q: "How many legs does a spider have?", a: "8", wrong: ["6", "4", "10"], level: 1, emoji: "🕷️",
      fact: "Spiders have 8 legs, so they're not insects. Insects have 6!" },
    { q: "How many legs does an insect have?", a: "6", wrong: ["8", "4", "10"], level: 1, emoji: "🐞",
      fact: "Adult insects have 6 legs and 3 body parts: head, thorax and abdomen." },
    { q: "What does a caterpillar turn into?", a: "A butterfly or moth", wrong: ["A beetle", "A bee", "A worm"], level: 1, emoji: "🐛",
      fact: "Inside its chrysalis or cocoon, a caterpillar completely rebuilds its body!" },
    { q: "What does a giant panda mostly eat?", a: "Bamboo", wrong: ["Fish", "Honey", "Bananas"], level: 1, emoji: "🐼",
      fact: "Pandas spend about half the day munching bamboo." },
    { q: "Which bird can't fly but is the fastest runner of all birds?", a: "Ostrich", wrong: ["Penguin", "Eagle", "Parrot"], level: 1, emoji: "🥚",
      fact: "Ostriches can run about 70 km/h. They're the biggest birds in the world and lay the biggest eggs too!" },
    { q: "Which animal changes colour?", a: "Chameleon", wrong: ["Zebra", "Elephant", "Penguin"], level: 1, emoji: "🎨",
      fact: "Chameleons change colour to show their mood and to warm up or cool down, as well as to blend in." },
    { q: "Which animal is called the 'king of the jungle', even though it lives on grassy plains?", a: "Lion", wrong: ["Tiger", "Gorilla", "Elephant"], level: 1, emoji: "👑",
      fact: "Most lions live in grasslands and savannas, not jungles!" },
    { q: "What do bees make from flower nectar?", a: "Honey", wrong: ["Milk", "Jam", "Maple syrup"], level: 1, emoji: "🐝",
      fact: "Honeybees do a 'waggle dance' to tell their hive where the best flowers are!" },
    { q: "How many hearts does an octopus have?", a: "3", wrong: ["1", "2", "8"], level: 2, emoji: "🐙",
      fact: "An octopus has three hearts and blue blood!" },
    { q: "Which mammal lays eggs?", a: "Platypus", wrong: ["Dolphin", "Bat", "Kangaroo"], level: 2, emoji: "🥚",
      fact: "The platypus and the echidna are the only mammals that lay eggs." },
    { q: "Which bird can fly backwards?", a: "Hummingbird", wrong: ["Eagle", "Owl", "Pigeon"], level: 2, emoji: "🐦",
      fact: "Hummingbirds beat their wings about 50 times a second, so they can hover and even fly backwards!" },
    { q: "Why are flamingos pink?", a: "Because of the food they eat", wrong: ["They're born pink", "They get sunburnt", "They roll in pink mud"], level: 2, emoji: "🦩",
      fact: "Flamingos eat tiny shrimp and algae full of pink colouring. Baby flamingos are grey!" },
    { q: "How do dolphins sleep?", a: "With half their brain at a time", wrong: ["On the sea floor", "They never sleep", "On the beach"], level: 2, emoji: "🐬",
      fact: "One half of a dolphin's brain stays awake so it can keep swimming and come up to breathe." },
    { q: "Which bird can turn its head almost all the way around?", a: "Owl", wrong: ["Duck", "Chicken", "Parrot"], level: 2, emoji: "🔄",
      fact: "Owls can turn their heads about 270 degrees, because their eyes can't move in their sockets." },
    { q: "What is an elephant's trunk?", a: "Its nose and top lip joined together", wrong: ["A long tooth", "An extra arm", "Its tail"], level: 2, emoji: "🐘",
      fact: "An elephant uses its trunk to smell, drink, grab food and even give hugs!" },
    { q: "Which animal can't jump?", a: "Elephant", wrong: ["Kangaroo", "Frog", "Rabbit"], level: 2, emoji: "⬆️",
      fact: "Elephants are too heavy, and their ankles too stiff, to jump. Even when they hurry, one foot always stays on the ground." },
    { q: "Which sea creature can grow back a lost arm?", a: "Starfish", wrong: ["Shark", "Whale", "Seahorse"], level: 2, emoji: "🌊",
      fact: "Starfish (sea stars) can grow back lost arms, and they don't even have a brain!" },
    { q: "How long can a koala sleep in one day?", a: "Up to about 20 hours", wrong: ["About 1 hour", "About 5 hours", "Koalas never sleep"], level: 2, emoji: "🐨",
      fact: "Koalas sleep so much because eucalyptus leaves give them very little energy." },
    { q: "Where do almost all penguins live?", a: "In the southern half of the world", wrong: ["At the North Pole", "In deserts", "In jungles"], level: 2, emoji: "🐧",
      fact: "Almost all penguins live south of the equator, and polar bears live in the far north, so they never meet in the wild!" },
    { q: "What do we call an animal that eats only plants?", a: "Herbivore", wrong: ["Carnivore", "Omnivore", "Insectivore"], level: 2, emoji: "🌿",
      fact: "Herbivores eat plants, carnivores eat meat, and omnivores (like bears, foxes and people) eat both!" },
    { q: "Which mammal can really flap its wings and fly?", a: "Bat", wrong: ["Flying squirrel", "Sugar glider", "Flying lemur"], level: 3, emoji: "☁️",
      fact: "Bats are the only mammals that truly fly. Flying squirrels and sugar gliders only glide." },
    { q: "Which animal can regrow its legs, and even bits of its heart?", a: "Axolotl", wrong: ["Hamster", "Pigeon", "Tortoise"], level: 3, emoji: "💧",
      fact: "Axolotls are smiley amphibians from Mexico with amazing healing powers." },
    { q: "Why do sloths sometimes look green?", a: "Tiny plants called algae grow in their fur", wrong: ["They eat too many leaves", "They paint themselves", "They're feeling cold"], level: 3, emoji: "🦥",
      fact: "Sloth hairs have tiny cracks that soak up rain like a sponge, so algae can grow there. Scientists think the green tint helps sloths hide in the trees." },
    { q: "What is a shark's skeleton made of?", a: "Cartilage, like your ears", wrong: ["Bone", "Shell", "Wood"], level: 3, emoji: "🦈",
      fact: "Sharks have no bones! Their skeletons are made of bendy cartilage, like your nose and ears." },
    { q: "Which tiny animal survived being left outside a spaceship, right in open space?", a: "Tardigrade (water bear)", wrong: ["Ant", "Ladybug", "Goldfish"], level: 3, emoji: "🚀",
      fact: "Tardigrades are about the size of a grain of sand and can survive freezing, drying out and even space!" },
    { q: "Which bird is the fastest animal on Earth when it dives?", a: "Peregrine falcon", wrong: ["Ostrich", "Penguin", "Hummingbird"], level: 3, emoji: "⚡",
      fact: "A diving peregrine falcon can go faster than 300 km/h!" },
    { q: "How do sea turtles choose where to lay their eggs?", a: "They go back to the area where they hatched", wrong: ["They pick the sandiest beach", "They follow dolphins", "Wherever the waves take them"], level: 3, emoji: "🐢",
      fact: "Mother sea turtles can swim thousands of kilometres and still find their way back to the stretch of coast where they hatched. Scientists think Earth's magnetism guides them!" },
    { q: "What colour is a polar bear's skin under its fur?", a: "Black", wrong: ["White", "Pink", "Orange"], level: 3, emoji: "❄️",
      fact: "Scientists think the black skin helps soak up the sun's warmth. The fur is actually see-through, not white!" },
  ],
});
