// 📚 The books question bank inside "Books & Pop Culture" (see culture.js for how it's mixed).
// level: 1 = easy, 2 = medium, 3 = hard. Facts must be true; when a story is told different ways, say "in the book".

import { bankTopic } from "../kit.js";

export const books = bankTopic({
  id: "books",
  title: "Book Club",
  emoji: "📚",
  eyebrow: "Book Club",
  guide: { who: "bookworm", place: "The library" }, // the bookworm from Adventures of Rufus
  questions: [
    // 🍫 Roald Dahl's stories
    { q: "In Roald Dahl's book, what does Charlie find inside his chocolate bar?", a: "A Golden Ticket", wrong: ["A silver coin", "A secret map", "A tiny key", "A gold star"], level: 1, emoji: "🍫",
      fact: "Only five Golden Tickets were hidden in Wonka bars all around the world." },
    { q: "In Matilda, who is Matilda's kind teacher?", a: "Miss Honey", wrong: ["Miss Plum", "Miss Sugar", "Miss Daisy", "Miss Pepper"], level: 1, emoji: "🏫",
      fact: "Matilda taught herself to read at three, and had read every children's book in her local library by the age of four and a quarter!" },
    { q: "In Matilda, what special power does Matilda discover?", a: "Moving things with her eyes", wrong: ["Talking to animals", "Turning herself invisible", "Flying like a bird", "Breathing underwater"], level: 2, emoji: "✨",
      fact: "She first uses it to tip a glass of water, with a newt inside, all over the horrible Miss Trunchbull!" },
    { q: "What does the BFG catch and keep in jars?", a: "Dreams", wrong: ["Fireflies", "Butterflies", "Snowflakes", "Raindrops"], level: 1, emoji: "👂",
      fact: "The BFG drinks frobscottle, a fizzy drink whose bubbles go down instead of up!" },
    { q: "In Fantastic Mr Fox, the three farmers are Boggis, Bunce and who?", a: "Bean", wrong: ["Biggs", "Bloggs", "Brown", "Bones"], level: 3, emoji: "🦊",
      fact: "Mr Fox and his four children dig tunnels right into the farmers' chicken houses and storehouses to fetch a feast." },
    { q: "In The Twits, what does Mrs Twit sneak into Mr Twit's spaghetti?", a: "Worms", wrong: ["Slugs", "Beetles", "Snails", "Tadpoles"], level: 2, emoji: "🍝",
      fact: "The Twits also keep a family of monkeys called the Muggle-Wumps, who play a brilliant trick on them in the end." },
    { q: "In James and the Giant Peach, which birds pull the peach through the sky?", a: "Seagulls", wrong: ["Pelicans", "Eagles", "Swans", "Pigeons"], level: 3, emoji: "🍑",
      fact: "The peach flies all the way across the ocean and lands on top of the Empire State Building in New York!" },

    // 🦉 Harry Potter (books 1-3)
    { q: "Which Hogwarts house is Harry Potter sorted into?", a: "Gryffindor", wrong: ["Slytherin", "Hufflepuff", "Ravenclaw"], level: 1, emoji: "🎩",
      fact: "The Sorting Hat thinks about putting Harry in Slytherin, until Harry asks it not to." },
    { q: "What is the name of Harry Potter's snowy owl?", a: "Hedwig", wrong: ["Errol", "Snowdrop", "Hooty", "Archimedes"], level: 1, emoji: "🦉",
      fact: "Hagrid buys her for Harry's 11th birthday, and Harry finds her name in a book called A History of Magic." },
    { q: "What is the wizard sport played on flying broomsticks called?", a: "Quidditch", wrong: ["Gobstones", "Exploding Snap", "Wizard chess", "Skyball"], level: 1, emoji: "🧹",
      fact: "Harry is his team's Seeker. Catching the tiny Golden Snitch wins 150 points and ends the game." },
    { q: "Which Hogwarts subject is all about magical plants?", a: "Herbology", wrong: ["Potions", "Transfiguration", "Charms", "Astronomy"], level: 2, emoji: "🏰",
      fact: "Herbology lessons happen in the greenhouses behind the castle, taught by Professor Sprout." },
    { q: "In Harry Potter, what kind of magical creature is Buckbeak?", a: "A hippogriff", wrong: ["A griffin", "A dragon", "A unicorn", "A phoenix"], level: 3, emoji: "🧙",
      fact: "A hippogriff is half horse, half eagle. You must bow to one and wait for it to bow back before you go near!" },

    // 📓 Diary of a Wimpy Kid
    { q: "In Diary of a Wimpy Kid, who is Greg Heffley's best friend?", a: "Rowley", wrong: ["Rodrick", "Manny", "Bryce", "Holly"], level: 1, emoji: "📓",
      fact: "Greg says his book is a journal, not a diary! His big brother is Rodrick and his little brother is Manny." },
    { q: "In Diary of a Wimpy Kid, what mouldy food sits on the school basketball court?", a: "A slice of cheese", wrong: ["A slice of pizza", "A banana peel", "An old sandwich", "A half-eaten apple"], level: 2, emoji: "🏀",
      fact: "Touch it and you get the dreaded Cheese Touch, which you can only get rid of by passing it on!" },

    // 🐶 Dog Man and Captain Underpants
    { q: "What job does Dog Man do?", a: "Police officer", wrong: ["Firefighter", "Teacher", "Chef", "Lifeguard"], level: 1, emoji: "🐶",
      fact: "In the stories, Dog Man comics are made by George and Harold, the same boys who made Captain Underpants." },
    { q: "In Dog Man, what kind of animal is Petey, the baddie?", a: "A cat", wrong: ["A rat", "A parrot", "A squirrel", "A frog"], level: 2, emoji: "🦹",
      fact: "Petey makes a little copy of himself called Li'l Petey, who turns out to be kind and good." },
    { q: "In Captain Underpants, what turns the hero back into Mr Krupp?", a: "Water on his head", wrong: ["Snapping fingers", "A loud sneeze", "A ringing bell", "A cold breeze"], level: 3, emoji: "🦸",
      fact: "Mr Krupp is George and Harold's head teacher. They hypnotised him, so a finger snap turns him into the hero." },

    // ⚡ Percy Jackson and Wings of Fire
    { q: "In The Lightning Thief, which Greek god is Percy Jackson's dad?", a: "Poseidon", wrong: ["Zeus", "Hades", "Apollo", "Hermes"], level: 2, emoji: "🏛️",
      fact: "Rick Riordan first made up Percy's adventures as bedtime stories for his son, who loved Greek myths." },
    { q: "In Percy Jackson, where do children of the Greek gods spend the summer?", a: "Camp Half-Blood", wrong: ["Camp Olympus", "Camp Thunderbolt", "Camp Starlight", "Camp Trident"], level: 3, emoji: "🏕️",
      fact: "Percy's teacher Mr Brunner turns out to be Chiron, a centaur who trains young heroes at the camp." },
    { q: "In Wings of Fire, which dragon tribe can change the colour of its scales?", a: "RainWings", wrong: ["MudWings", "SandWings", "IceWings", "SkyWings"], level: 3, emoji: "🐉",
      fact: "Pyrrhia has seven dragon tribes. Glory, one of the five dragonets in the first book, is a RainWing." },

    // 🌳 Picture-book favourites
    { q: "In The Gruffalo, which small animal walks through the wood, tricking everyone?", a: "A mouse", wrong: ["A rabbit", "A hedgehog", "A squirrel", "A frog"], level: 1, emoji: "🌳",
      fact: "Julia Donaldson wrote The Gruffalo and Axel Scheffler drew the pictures. It first came out in 1999." },
    { q: "In The Gruffalo, which animal does the mouse meet first?", a: "A fox", wrong: ["An owl", "A snake", "A badger", "A bear"], level: 2, emoji: "👣",
      fact: "Next come an owl and a snake. The mouse fools them all with tales of terrible tusks, orange eyes and purple prickles!" },
    { q: "What is Winnie-the-Pooh's favourite food?", a: "Honey", wrong: ["Jam", "Cheese", "Carrots", "Fish"], level: 1, emoji: "🐻",
      fact: "Pooh got part of his name from Winnie, a real bear at London Zoo that Christopher Robin Milne loved to visit." },
    { q: "Which of Pooh's friends doesn't appear until the second book, The House at Pooh Corner?", a: "Tigger", wrong: ["Piglet", "Eeyore", "Owl", "Rabbit", "Kanga"], level: 3, emoji: "🎈",
      fact: "Tigger, Piglet, Eeyore, Kanga and Roo were based on real toys owned by A. A. Milne's son, Christopher Robin." },
    { q: "In Where the Wild Things Are, what is the boy called?", a: "Max", wrong: ["Sam", "Tom", "Ben", "Leo"], level: 2, emoji: "👑",
      fact: "Max wears a wolf suit, and when he sails home from the Wild Things his supper is waiting, still hot." },
    { q: "In Green Eggs and Ham, who keeps asking someone to try the food?", a: "Sam-I-am", wrong: ["The Grinch", "Horton", "The Lorax", "Thing One"], level: 2, emoji: "🍳",
      fact: "Dr. Seuss wrote the whole book using just 50 different words, after his publisher bet him he couldn't!" },
    { q: "In How the Grinch Stole Christmas!, how many sizes does the Grinch's heart grow?", a: "Three", wrong: ["Two", "Four", "Five", "Ten"], level: 2, emoji: "🎄",
      fact: "At the start, the Grinch's heart is 'two sizes too small'. He lives above Who-ville with his dog, Max." },
    { q: "What does the Very Hungry Caterpillar become at the end of the book?", a: "A butterfly", wrong: ["A dragonfly", "A ladybird", "A bumblebee", "A grasshopper"], level: 1, emoji: "🐛",
      fact: "Eric Carle made the pictures by painting tissue paper, then cutting it out and gluing it down as a collage." },

    // 🗝️ Classic stories
    { q: "In Alice's Adventures in Wonderland, who does Alice follow into Wonderland?", a: "The White Rabbit", wrong: ["The Cheshire Cat", "The Mad Hatter", "The Dormouse", "The Caterpillar"], level: 1, emoji: "👧",
      fact: "He is always in a hurry, and checks the time on a watch he takes out of his waistcoat pocket." },
    { q: "In Alice in Wonderland, which grinning animal can slowly vanish into thin air?", a: "The Cheshire Cat", wrong: ["The March Hare", "The Dormouse", "The Mock Turtle", "The Caterpillar"], level: 2, emoji: "🃏",
      fact: "People said 'grinning like a Cheshire cat' long before the book came out. It was in a dictionary by 1788!" },
    { q: "Where do Peter Pan and the Lost Boys live?", a: "Neverland", wrong: ["Wonderland", "Narnia", "Toyland", "Lilliput"], level: 1, emoji: "🧚",
      fact: "In 1929, J. M. Barrie gave the rights to Peter Pan to Great Ormond Street, a children's hospital in London." },
    { q: "In The Lion, the Witch and the Wardrobe, what is the great lion called?", a: "Aslan", wrong: ["Tumnus", "Caspian", "Leo", "Rex"], level: 1, emoji: "❄️",
      fact: "'Aslan' is the Turkish word for lion. C. S. Lewis found the name in the notes of an old Arabian Nights book." },
    { q: "In Narnia, what kind of creature is Mr Tumnus?", a: "A faun", wrong: ["A dwarf", "A centaur", "A beaver", "An elf"], level: 2, emoji: "🌲",
      fact: "A faun has goat's legs and horns. Lucy meets him by a lamp-post in the snow, and he invites her home for tea." },
    { q: "In Narnia, which sweet does the White Witch give Edmund?", a: "Turkish delight", wrong: ["Toffee", "Fudge", "Marshmallows", "Liquorice"], level: 2, emoji: "🍬",
      fact: "The White Witch keeps Narnia stuck in winter all year round, and Christmas never comes." },
    { q: "In Charlotte's Web, what kind of animal is Wilbur?", a: "A pig", wrong: ["A goat", "A sheep", "A cow", "A horse"], level: 1, emoji: "🕸️",
      fact: "Charlotte the spider weaves words like 'Some Pig' and 'Terrific' into her web to show how special he is." },
    { q: "In Charlotte's Web, what is the name of the greedy rat?", a: "Templeton", wrong: ["Scabbers", "Whiskers", "Nibbles", "Barnaby"], level: 3, emoji: "🎡",
      fact: "Templeton fetches new words for Charlotte's web, like 'Radiant', which he finds written on a box of soap flakes." },
    { q: "Which country does Paddington Bear come from?", a: "Peru", wrong: ["Brazil", "Mexico", "Chile", "Canada"], level: 2, emoji: "🧳",
      fact: "The Brown family find him at Paddington Station in London, wearing a label asking people to look after him." },
    { q: "What is Paddington Bear's favourite food?", a: "Marmalade", wrong: ["Honey", "Peanut butter", "Cheese", "Chocolate spread"], level: 1, emoji: "🧸",
      fact: "Michael Bond got the idea from a lonely toy bear he saw on a shop shelf on Christmas Eve 1956." },
    { q: "In The Jungle Book, what is the name of the boy raised by wolves?", a: "Mowgli", wrong: ["Akela", "Kimba", "Tarzan", "Raja"], level: 1, emoji: "🌴",
      fact: "In Rudyard Kipling's book from 1894, Mother Wolf names him. 'Mowgli the Frog I will call thee,' she says." },
    { q: "In The Jungle Book, what kind of animal is Bagheera?", a: "A black panther", wrong: ["A striped tiger", "A brown bear", "A grey wolf", "A rock python"], level: 2, emoji: "🐾",
      fact: "Kipling says Bagheera is 'inky black all over'. He shows Mowgli how to climb trees, and Baloo the bear teaches him the Law of the Jungle." },
    { q: "In The Hobbit, what is the name of the dragon sleeping on the treasure?", a: "Smaug", wrong: ["Norbert", "Toothless", "Falkor", "Puff"], level: 3, emoji: "⛰️",
      fact: "On the way, Bilbo finds a magic ring that makes him invisible whenever he puts it on." },
    { q: "Pippi Longstocking lives with a monkey and which other animal?", a: "A horse", wrong: ["A pig", "A goat", "A parrot", "A cow"], level: 3, emoji: "🐒",
      fact: "Pippi is so strong she can lift up her horse! Her monkey is called Mr Nilsson." },
    { q: "In The Secret Garden, which bird helps Mary find the buried key?", a: "A robin", wrong: ["A magpie", "A blackbird", "A sparrow", "A crow"], level: 3, emoji: "🗝️",
      fact: "The garden had been locked up for ten years, until Mary found her way in and brought it back to life." },

    // 🌟 Newer favourites
    { q: "In The Wild Robot, what baby animal does Roz the robot look after?", a: "A gosling", wrong: ["A bear cub", "A fawn", "A baby owl", "A beaver kit"], level: 2, emoji: "🤖",
      fact: "Roz is short for ROZZUM unit 7134, and the little goose is called Brightbill." },
    { q: "In Wonder, which boy starts fifth grade at Beecher Prep after years of learning at home?", a: "Auggie Pullman", wrong: ["Max Turner", "Charlie Brooks", "Ollie Bennett", "Sam Fletcher"], level: 3, emoji: "🌟",
      fact: "His teacher, Mr Browne, gives the class a precept, which is a wise motto, every month." },
    { q: "What is the name of the newspaper Geronimo Stilton runs?", a: "The Rodent's Gazette", wrong: ["The Daily Cheese", "The Mouse Times", "The Squeaky News", "The Whisker Post"], level: 3, emoji: "📰",
      fact: "Geronimo is a mouse who lives in New Mouse City on Mouse Island. His sister Thea writes for his paper too." },
    { q: "In the Tom Gates books, what is Tom's favourite snack?", a: "Caramel wafers", wrong: ["Cheese puffs", "Carrot sticks", "Fish fingers", "Pickled onions"], level: 3, emoji: "🎸",
      fact: "Tom plays guitar in a band called DogZombies with his best friend and next-door neighbour, Derek." },

    // 🐢 Fables and fairy tales
    { q: "In Aesop's fable of the Tortoise and the Hare, why does the hare lose?", a: "He stops for a nap", wrong: ["He trips over a rock", "He gets lost", "He stops to eat lunch", "His legs get tired"], level: 1, emoji: "🐢",
      fact: "Aesop is said to have been a storyteller in ancient Greece more than 2,500 years ago." },
    { q: "In Aesop's fable, a fox can't reach some fruit, so says it must be sour. What fruit?", a: "Grapes", wrong: ["Apples", "Cherries", "Plums", "Pears"], level: 2, emoji: "🦊",
      fact: "This fable gave us the saying 'sour grapes', for pretending you never wanted something you couldn't get." },
    { q: "In Goldilocks and the Three Bears, whose porridge is just right?", a: "Baby Bear's", wrong: ["Daddy Bear's", "Mummy Bear's", "Grandpa Bear's"], level: 1, emoji: "🥣",
      fact: "In the first published version, by Robert Southey in 1837, the visitor was a rude old woman, not a girl!" },
    { q: "In Cinderella, what does the fairy godmother turn into a coach?", a: "A pumpkin", wrong: ["A watermelon", "A turnip", "A cabbage", "A teapot"], level: 1, emoji: "👠",
      fact: "In Charles Perrault's version from 1697, she also turns mice into horses and a rat into the coachman." },
    { q: "In Jack and the Beanstalk, what does Jack swap for the magic beans?", a: "A cow", wrong: ["A goat", "A pig", "A horse", "A sheep"], level: 1, emoji: "🌱",
      fact: "In the old English version written down by Joseph Jacobs, the cow is called Milky-white." },

    // 🧹 Julia Donaldson, Judith Kerr and other picture-book favourites
    { q: "In Room on the Broom, what does the witch lose first in the wind?", a: "Her hat", wrong: ["Her wand", "Her bow", "Her cat", "Her cloak"], level: 2, emoji: "🧹",
      fact: "A dog finds the hat, a bird finds her bow and a frog finds her wand, and each one asks for a ride on the broom." },
    { q: "In The Snail and the Whale, how does the snail get help for the stranded whale?", a: "She writes on a blackboard", wrong: ["She rings a big bell", "She sends a seagull", "She sings very loudly", "She calls a lifeboat"], level: 2, emoji: "🐌",
      fact: "At the very start, the snail asks for a lift by writing on a rock with her silvery slime trail." },
    { q: "In Zog, what does the clumsy young dragon long to win at dragon school?", a: "A golden star", wrong: ["A silver cup", "A shiny medal", "A golden crown", "A blue ribbon"], level: 2, emoji: "🐉",
      fact: "Princess Pearl patches Zog up after every bump, and in the end she becomes a doctor!" },
    { q: "In The Tiger Who Came to Tea, where does Sophie's family go for supper after the tiger leaves?", a: "To a café", wrong: ["To a picnic", "To Granny's house", "To a pizza party", "To the seaside"], level: 2, emoji: "🐯",
      fact: "The tiger eats every bit of food in the house and even drinks all the water in the tap!" },
    { q: "What is special about Elmer the elephant?", a: "He's patchwork", wrong: ["He's bright pink", "He's very tiny", "He can fly", "He's spotty"], level: 1, emoji: "🐘",
      fact: "Once a year the elephants decorate themselves for Elmer's Day, and Elmer paints himself elephant-grey!" },
    { q: "In The Day the Crayons Quit, how do Duncan's crayons tell him they're unhappy?", a: "They write him letters", wrong: ["They hide in a sock", "They draw a map", "They sing a song", "They stop working"], level: 2, emoji: "🖍️",
      fact: "Peach Crayon won't come out of the box, because its paper wrapper was peeled off and it feels undressed!" },
    { q: "Who was the very first Mr Men character?", a: "Mr Tickle", wrong: ["Mr Happy", "Mr Greedy", "Mr Bump", "Mr Strong"], level: 3, emoji: "🧡",
      fact: "Roger Hargreaves dreamed him up in 1971, after his son Adam asked what a tickle looks like." },
    { q: "In The Tale of Peter Rabbit, what colour is Peter's jacket?", a: "Blue", wrong: ["Red", "Green", "Yellow", "Brown"], level: 2, emoji: "🐰",
      fact: "Beatrix Potter first told Peter's story in a picture letter to a little boy called Noel Moore in 1893." },

    // 🎩 Dr. Seuss
    { q: "In The Cat in the Hat, what is the weather like outside?", a: "Rainy", wrong: ["Snowy", "Sunny", "Windy", "Foggy"], level: 1, emoji: "🎩",
      fact: "Dr. Seuss wrote it using only 236 different words, so children could read it all by themselves." },
    { q: "In The Lorax, what does the Lorax speak for?", a: "The trees", wrong: ["The fish", "The birds", "The bears", "The flowers"], level: 1, emoji: "🌳",
      fact: "The Once-ler chops down Truffula trees to knit Thneeds, which he says everyone needs." },
    { q: "In Horton Hears a Who!, what kind of animal is Horton?", a: "An elephant", wrong: ["A hippo", "A rhino", "A walrus", "A bear"], level: 1, emoji: "🐘",
      fact: "A whole town of Whos lives on a tiny speck of dust, and only Horton's big ears can hear them." },

    // 🍫 More Roald Dahl
    { q: "Who does George make his marvellous medicine for?", a: "His grandma", wrong: ["His teacher", "His dad", "His dog", "His sister"], level: 1, emoji: "🧪",
      fact: "His dad loves how the medicine makes animals grow giant, but George can never make the same mixture again." },
    { q: "In Roald Dahl's Esio Trot, what kind of pet is Alfie?", a: "A tortoise", wrong: ["A hamster", "A goldfish", "A rabbit", "A parrot"], level: 3, emoji: "🐢",
      fact: "'Esio Trot' is 'tortoise' spelled backwards! Mr Hoppy swaps Alfie for bigger and bigger tortoises to make Mrs Silver happy." },
    { q: "In Charlie and the Chocolate Factory, which greedy boy falls into the chocolate river?", a: "Augustus Gloop", wrong: ["Mike Teavee", "Charlie Bucket", "Grandpa Joe", "Willy Wonka"], level: 2, emoji: "🍫",
      fact: "A waterfall churns up the river's chocolate to make it light and frothy." },
    { q: "In Matilda, what does Bruce Bogtrotter have to eat in front of the whole school?", a: "A giant chocolate cake", wrong: ["A bowl of cold porridge", "A huge jelly", "A plate of sprouts", "A big trifle"], level: 2, emoji: "🎂",
      fact: "He eats every last crumb, and all the children cheer him on!" },

    // 🦉 More Harry Potter
    { q: "Which platform does the Hogwarts Express leave from?", a: "Nine and three-quarters", wrong: ["Seven and a half", "Ten and a quarter", "Twelve and a half", "Thirteen"], level: 1, emoji: "🚂",
      fact: "At King's Cross station in London, there's a real Platform 9¾ sign, with a luggage trolley half-way into the wall." },
    { q: "In Harry Potter, what is the name of Ron Weasley's pet rat?", a: "Scabbers", wrong: ["Crookshanks", "Trevor", "Fang", "Nibbles"], level: 2, emoji: "🐀",
      fact: "Hermione's pet is a clever ginger cat called Crookshanks." },
    { q: "Which wizard sweets come in every flavour, even earwax?", a: "Bertie Bott's Beans", wrong: ["Chocolate Frogs", "Sugar Quills", "Pepper Imps", "Fizzing Whizzbees"], level: 2, emoji: "🍬",
      fact: "Chocolate Frogs come with a card of a famous witch or wizard, and the frogs can really hop!" },

    // 📓 Funny books and their makers
    { q: "Who wrote and drew Diary of a Wimpy Kid?", a: "Jeff Kinney", wrong: ["Dav Pilkey", "Liz Pichon", "David Walliams", "Rick Riordan"], level: 2, emoji: "✏️",
      fact: "Jeff Kinney first put Greg's diary on a website in 2004, three years before the first book came out." },
    { q: "In The Worst Witch, what is Mildred Hubble's school called?", a: "Miss Cackle's Academy", wrong: ["Hogwarts", "Broomhill School", "Spellwood Academy", "Grimstone Hall"], level: 3, emoji: "🧙‍♀️",
      fact: "All the other young witches get black cats, but Mildred ends up with a tabby who can't sit on a broomstick properly." },

    // 🗝️ More classics
    { q: "In Dick King-Smith's book, which piglet learns to herd sheep like a sheepdog?", a: "Babe", wrong: ["Wilbur", "Pinky", "Percy", "Hamlet"], level: 2, emoji: "🐷",
      fact: "Babe asks the sheep politely instead of bossing them about. The book is called The Sheep-Pig, and became the film Babe." },
    { q: "Where do the Borrowers live?", a: "Under the floorboards", wrong: ["Inside a teapot", "In a bird's nest", "Behind a painting", "In a toy box"], level: 3, emoji: "🧷",
      fact: "They 'borrow' little things from the humans upstairs, like postage stamps to hang as pictures on their walls." },
    { q: "In The Wind in the Willows, what does Toad love more than anything?", a: "Motor cars", wrong: ["Trains", "Gardening", "Painting", "Kites"], level: 3, emoji: "🐸",
      fact: "Toad's friends are Mole, Ratty and Badger, and he lives in a grand house called Toad Hall." },
    { q: "Where does Heidi go to live with her grandfather?", a: "The Swiss Alps", wrong: ["The Scottish Highlands", "The Andes", "The Himalayas", "The Rocky Mountains"], level: 2, emoji: "⛰️",
      fact: "Heidi was written by Swiss author Johanna Spyri more than 140 years ago, and is still loved all over the world." },
    { q: "In The Little Prince, what flower does the prince look after on his tiny planet?", a: "A rose", wrong: ["A tulip", "A daisy", "A sunflower", "A daffodil"], level: 3, emoji: "🪐",
      fact: "His planet also has three tiny volcanoes, and he cleans them out carefully, even the one that's gone quiet." },
    { q: "In Enid Blyton's Famous Five, what kind of animal is Timmy?", a: "A dog", wrong: ["A cat", "A pony", "A parrot", "A goat"], level: 2, emoji: "🐕",
      fact: "Timmy belongs to George, whose real name is Georgina. Her family owns a whole island: Kirrin Island!" },
    { q: "What kind of creatures are the Moomins?", a: "Trolls", wrong: ["Hippos", "Elves", "Bears", "Ghosts"], level: 3, emoji: "🌲",
      fact: "Tove Jansson, from Finland, wrote the first Moomin book in 1945. Moomins sleep right through the winter!" },
    { q: "What is the name of Tintin's little white dog?", a: "Snowy", wrong: ["Patch", "Buster", "Pip", "Biscuit"], level: 2, emoji: "🐶",
      fact: "In the original French comics by Hergé, Snowy is called Milou." },
    { q: "In The House at Pooh Corner, what game do the friends play by dropping sticks off a bridge?", a: "Poohsticks", wrong: ["Twig Race", "Bridge Ball", "River Run", "Splashsticks"], level: 1, emoji: "🌉",
      fact: "There's a real Poohsticks Bridge in Ashdown Forest in England, and people still go there to play." },

    // 📖 Book words
    { q: "What do we call the person who draws the pictures in a book?", a: "The illustrator", wrong: ["The author", "The editor", "The publisher", "The librarian"], level: 1, emoji: "🖍️",
      fact: "Quentin Blake drew the pictures for lots of Roald Dahl's books, starting with The Enormous Crocodile in 1978." },
    { q: "What do we call books full of true facts, like a book about sharks?", a: "Non-fiction", wrong: ["Fiction", "Fairy tales", "Poetry", "Fantasy"], level: 1, emoji: "🦈",
      fact: "'Fiction' means made-up stories. It comes from a Latin word meaning to shape, like shaping clay." },
    { q: "What is the short bit on the back cover telling you what a book is about?", a: "The blurb", wrong: ["The index", "The glossary", "The contents", "The spine"], level: 2, emoji: "📖",
      fact: "The word 'blurb' caught on thanks to a joke book cover by American writer Gelett Burgess, starring a made-up 'Miss Belinda Blurb'!" },
    { q: "Which part of a book explains what the tricky words mean?", a: "The glossary", wrong: ["The index", "The blurb", "The contents", "The spine"], level: 2, emoji: "🔤",
      fact: "The word comes from 'glossa', ancient Greek for tongue, which also meant a strange word that needs explaining." },
  ],
});
