// 🎬 The movie and games question banks inside "Books & Pop Culture" (see culture.js for how they're mixed).
// level: 1 = easy, 2 = medium, 3 = hard. Only films rated U/PG (G/PG) and games rated PEGI 3-7 / E-E10+.

import { bankTopic } from "../kit.js";

export const movies = bankTopic({
  id: "movies",
  title: "Movie Magic",
  emoji: "🎬",
  eyebrow: "Movie Magic",
  guide: { who: "felix", place: "Movie night" }, // Rufus's dad Felix brings the popcorn
  questions: [
    // ---------- Pixar ----------
    { q: "In Toy Story, what is the name of Andy's cowboy doll?", a: "Woody", wrong: ["Rex", "Hamm", "Slinky", "Bo Peep"], level: 1, emoji: "🤠",
      fact: "Andy writes his name on the bottom of Woody's boot to show that the cowboy is his." },
    { q: "Which Toy Story toy thinks he is a real space ranger?", a: "Buzz Lightyear", wrong: ["Woody", "Rex", "Mr. Potato Head", "Hamm"], level: 1, emoji: "🚀",
      fact: "In 2008 a real Buzz Lightyear toy flew to the International Space Station and stayed there for over a year!" },
    { q: "In the first Toy Story, where do Woody and Buzz meet the three-eyed aliens?", a: "Pizza Planet", wrong: ["Al's Toy Barn", "Sunnyside Daycare", "Andy's attic"], level: 2, emoji: "👽",
      fact: "Pixar hides the Pizza Planet truck or logo in almost every one of its films. See if you can spot it!" },
    { q: "In Finding Nemo, which forgetful fish helps Marlin search for his son?", a: "Dory", wrong: ["Gill", "Bubbles", "Peach", "Squirt"], level: 1, emoji: "🌊",
      fact: "Dory is a blue tang, also called a regal tang, and she can read and even speak whale!" },
    { q: "In Finding Nemo, what kind of animal is Crush, the surfer dude?", a: "A sea turtle", wrong: ["A dolphin", "A shark", "A whale", "A stingray"], level: 2, emoji: "🏄",
      fact: "Crush says he's 150 years old and still young! He rides the East Australian Current like a giant water slide." },
    { q: "In Finding Dory, what kind of sea creature is grumpy Hank?", a: "An octopus", wrong: ["A squid", "A jellyfish", "A starfish", "A seahorse"], level: 3, emoji: "🌊",
      fact: "Hank has lost one arm, so Dory calls him a 'septopus'. Like real octopuses, he can change colour to hide." },
    { q: "In Monsters, Inc., what do monsters collect from children to power their city?", a: "Screams", wrong: ["Snores", "Tears", "Sneezes", "Dreams"], level: 1, emoji: "🚪",
      fact: "By the end, the monsters find out that children's laughs make even more power than screams." },
    { q: "In Monsters, Inc., what does little Boo call Sulley?", a: "Kitty", wrong: ["Puppy", "Teddy", "Fluffy", "Bear"], level: 2, emoji: "🚪",
      fact: "Sulley's fur has over 2 million hairs, and the computers had to work out how every one of them moved." },
    { q: "In The Incredibles, what is Violet's main superpower?", a: "Turning invisible", wrong: ["Super speed", "Super stretching", "Super strength", "Freezing things"], level: 2, emoji: "🦸",
      fact: "Violet can also make force fields, and she learns to use them to protect her family." },
    { q: "In The Incredibles, who designs the heroes' super suits?", a: "Edna Mode", wrong: ["Frozone", "Mirage", "Syndrome", "Rick Dicker"], level: 2, emoji: "🧵",
      fact: "Edna's number one rule for super suits is short and simple: no capes!" },
    { q: "In Cars, what kind of vehicle is Mater?", a: "A tow truck", wrong: ["A fire engine", "A police car", "A tractor", "A school bus"], level: 1, emoji: "🏁",
      fact: "Mater is Lightning McQueen's best friend, and he's brilliant at driving backwards." },
    { q: "In Cars, what is Lightning McQueen's racing number?", a: "95", wrong: ["43", "86", "51", "7"], level: 3, emoji: "🏁",
      fact: "95 is a nod to 1995, the year Pixar's first film, Toy Story, came out." },
    { q: "In Ratatouille, which famous chef wrote the cookbook Remy loves?", a: "Gusteau", wrong: ["Skinner", "Ego", "Linguini", "Colette"], level: 3, emoji: "🍲",
      fact: "Gusteau's book is called Anyone Can Cook!, and his restaurant is in Paris, where Remy dreams of cooking." },
    { q: "What is WALL-E's job on the empty, messy Earth?", a: "Cleaning up rubbish", wrong: ["Growing food", "Delivering post", "Building rockets", "Fixing cars"], level: 1, emoji: "🤖",
      fact: "WALL-E stands for Waste Allocation Load Lifter: Earth-Class." },
    { q: "In WALL-E, what kind of animal is WALL-E's little pet friend?", a: "A cockroach", wrong: ["A mouse", "A frog", "A pigeon", "A spider"], level: 3, emoji: "🌱",
      fact: "The cockroach never gets a name in the film, but the film-makers called him Hal." },
    { q: "In Up, how does Carl make his house fly?", a: "With thousands of balloons", wrong: ["With a giant kite", "With rocket engines", "With a huge propeller", "With magic dust"], level: 1, emoji: "🏠",
      fact: "For the moment the house lifts off, Pixar's computers made 20,622 balloons!" },
    { q: "In Up, what kind of animal is Kevin?", a: "A giant bird", wrong: ["A big dog", "A kangaroo", "A lizard", "A monkey"], level: 2, emoji: "🗺️",
      fact: "Russell names the bird Kevin, then finds out Kevin is actually a mum with chicks to feed!" },
    { q: "In Inside Out, which of Riley's emotions is blue?", a: "Sadness", wrong: ["Joy", "Anger", "Fear", "Disgust"], level: 1, emoji: "🧠",
      fact: "Riley is 11 in the first film, and her emotions work together at a control desk in Headquarters." },
    { q: "In Inside Out 2, which new emotion is orange and full of worries?", a: "Anxiety", wrong: ["Envy", "Ennui", "Embarrassment", "Nostalgia"], level: 2, emoji: "🧠",
      fact: "Riley is 13 now, and four new emotions move into Headquarters: Anxiety, Envy, Ennui and Embarrassment." },
    { q: "In Coco, what does Miguel dream of becoming?", a: "A musician", wrong: ["A shoemaker", "A footballer", "A painter", "A chef"], level: 1, emoji: "🌼",
      fact: "Miguel's family have been shoemakers for generations, and music is banned in their home." },
    { q: "In Coco, what breed of dog is Miguel's friend Dante?", a: "A Xolo", wrong: ["A Chihuahua", "A poodle", "A dachshund", "A pug"], level: 3, emoji: "🌼",
      fact: "Xolo is short for Xoloitzcuintli, often called Mexico's national dog. Lots of Xolos have no fur at all, just like Dante!" },
    { q: "In Luca, what kind of creatures are Luca and Alberto?", a: "Sea monsters", wrong: ["Aliens", "Dragons", "Robots", "Fairies"], level: 2, emoji: "🍝",
      fact: "When they're dry they look just like ordinary boys, but a splash of water turns them back." },
    { q: "In Elemental, what is Wade made of?", a: "Water", wrong: ["Fire", "Air", "Earth"], level: 2, emoji: "🏙️",
      fact: "Wade cries very easily! He lives in Element City, where fire, water, earth and air folk live side by side." },

    // ---------- Disney ----------
    { q: "In Frozen, what is the name of the snowman who loves warm hugs?", a: "Olaf", wrong: ["Sven", "Kristoff", "Hans", "Marshmallow"], level: 1, emoji: "☃️",
      fact: "Olaf's nose is a carrot, and Sven the reindeer keeps trying to nibble it!" },
    { q: "In Frozen, what is the name of Anna and Elsa's kingdom?", a: "Arendelle", wrong: ["Corona", "Agrabah", "Atlantica", "The Southern Isles"], level: 2, emoji: "❄️",
      fact: "To design it, the film-makers visited Norway to study its fjords, wooden churches and colourful old towns." },
    { q: "In Frozen II, what is the name of the little fire spirit Elsa befriends?", a: "Bruni", wrong: ["Gale", "Nokk", "Pascal"], level: 3, emoji: "🍂",
      fact: "Bruni is a salamander. Real salamanders are amphibians, but in old European stories they were linked with fire." },
    { q: "In Moana, what kind of animal is Heihei?", a: "A rooster", wrong: ["A pig", "A crab", "A parrot", "A goat"], level: 1, emoji: "🏝️",
      fact: "Heihei was nearly cut from the film, until the story team rewrote him as a lovable, very silly bird." },
    { q: "In Moana, what magical object lets Maui change into animals?", a: "A giant fish hook", wrong: ["A seashell necklace", "A wooden paddle", "A feather cloak", "A coconut drum"], level: 2, emoji: "🌊",
      fact: "Maui's tattoos can move, and a tiny tattoo version of him, Mini Maui, acts like his conscience." },
    { q: "In Encanto, which Madrigal grandchild has no magic gift?", a: "Mirabel", wrong: ["Isabela", "Luisa", "Dolores", "Camilo"], level: 1, emoji: "🦋",
      fact: "Mirabel wears green glasses, and her skirt is stitched with symbols for her family, like flowers for Isabela." },
    { q: "In Zootopia (Zootropolis in the UK), what animal is Nick Wilde?", a: "A fox", wrong: ["A wolf", "A rabbit", "A raccoon", "A cheetah"], level: 1, emoji: "🏙️",
      fact: "Nick teams up with Judy Hopps, the city's very first bunny police officer, to solve a mystery." },
    { q: "In Big Hero 6, what is the name of the big, soft, huggable robot?", a: "Baymax", wrong: ["Hiro", "Wasabi", "Fred", "GoGo"], level: 1, emoji: "🤖",
      fact: "The film is set in San Fransokyo, a made-up city that mixes San Francisco and Tokyo." },
    { q: "In Wreck-It Ralph, which arcade game does Vanellope live in?", a: "Sugar Rush", wrong: ["Hero's Duty", "Fix-It Felix Jr.", "Pac-Man", "Tapper"], level: 3, emoji: "🕹️",
      fact: "Every kart in Sugar Rush is made of sweets, and Ralph helps Vanellope make her very own." },
    { q: "In The Lion King, what kind of animal is Pumbaa?", a: "A warthog", wrong: ["A meerkat", "A hyena", "A hippo", "A rhino"], level: 1, emoji: "🦁",
      fact: "Pumbaa and his meerkat pal Timon live by the motto 'hakuna matata', which means 'no worries' in Swahili." },
    { q: "In The Lion King, what kind of bird is Zazu?", a: "A hornbill", wrong: ["A parrot", "A toucan", "A flamingo", "A vulture"], level: 3, emoji: "🦁",
      fact: "Zazu is a red-billed hornbill, a bird that really lives on the African savannah." },
    { q: "In Aladdin, what is the name of the hero's cheeky pet monkey?", a: "Abu", wrong: ["Iago", "Rajah", "Jafar", "Sultan"], level: 2, emoji: "🧞",
      fact: "Princess Jasmine's pet is Rajah, a tiger, and Jafar's sidekick Iago is a parrot." },
    { q: "In The Little Mermaid, what does Scuttle tell Ariel a fork is called?", a: "A dinglehopper", wrong: ["A snarfblatt", "A twirlywhirl", "A combinator", "A noodle-scoop"], level: 3, emoji: "🍴",
      fact: "Scuttle also calls a pipe a 'snarfblatt' and says it makes music, but when he blows it, out comes seaweed!" },

    // ---------- DreamWorks ----------
    { q: "What kind of creature is Shrek, who lives in a swamp?", a: "An ogre", wrong: ["A troll", "A giant", "A goblin", "A dragon"], level: 1, emoji: "🏰",
      fact: "Before the films, Shrek! was a picture book by William Steig, published in 1990." },
    { q: "In How to Train Your Dragon, what is the name of Hiccup's dragon?", a: "Toothless", wrong: ["Stormfly", "Meatlug", "Hookfang", "Cloudjumper"], level: 1, emoji: "🐉",
      fact: "Toothless is a Night Fury, and he got his name because he can pull his teeth back into his gums." },
    { q: "In How to Train Your Dragon, what is the name of Hiccup's island home?", a: "Berk", wrong: ["Arendelle", "Motunui", "Atlantica", "Neverland"], level: 3, emoji: "🐉",
      fact: "The films are based on a series of books by British author Cressida Cowell." },
    { q: "In Kung Fu Panda, what kind of bird is Po's dad, Mr. Ping?", a: "A goose", wrong: ["A duck", "A swan", "A crane", "A peacock"], level: 3, emoji: "🐼",
      fact: "Mr. Ping runs a noodle shop, and he adopted Po when Po was a baby." },
    { q: "In Madagascar, what animal is Marty?", a: "A zebra", wrong: ["A lion", "A giraffe", "A hippo", "A lemur"], level: 1, emoji: "🏝️",
      fact: "Marty's wish on his 10th birthday, to see the wild, kicks off the whole adventure." },
    { q: "In Trolls, what is the name of the happy pink troll who becomes queen?", a: "Poppy", wrong: ["Branch", "Biggie", "Smidge", "Cooper"], level: 1, emoji: "🌈",
      fact: "The Trolls films are based on troll dolls first made by Thomas Dam in Denmark in the 1950s." },
    { q: "In Kung Fu Panda, what kind of animal is Master Oogway?", a: "A tortoise", wrong: ["A frog", "A snail", "A crocodile", "An armadillo"], level: 2, emoji: "🥋",
      fact: "Oogway is a Galápagos tortoise, and he's the one who surprises everyone by choosing Po as the Dragon Warrior." },
    { q: "In The Bad Guys, who is the leader of the gang?", a: "Mr. Wolf", wrong: ["Mr. Snake", "Mr. Shark", "Mr. Piranha", "Ms. Tarantula"], level: 2, emoji: "😎",
      fact: "The films are based on the funny book series by Australian author Aaron Blabey." },

    // ---------- Illumination ----------
    { q: "What is the Minions' favourite food?", a: "Bananas", wrong: ["Broccoli", "Carrots", "Fish"], level: 1, emoji: "🥽",
      fact: "Minions speak their own language, Minionese, a jumble of words from Spanish, French, Italian and more." },
    { q: "In Sing, what kind of animal is Buster Moon, who runs the theatre?", a: "A koala", wrong: ["A pig", "A gorilla", "A porcupine", "A mouse"], level: 2, emoji: "🎤",
      fact: "Buster's dad washed cars every day for 30 years to help him buy the theatre." },
    { q: "In The Super Mario Bros. Movie, where do Mario and Luigi run their plumbing business?", a: "Brooklyn", wrong: ["London", "Rome", "Chicago", "Tokyo"], level: 3, emoji: "🍄",
      fact: "While fixing a leak under the city, the brothers get sucked into a warp pipe that takes them to a magical new world." },

    // ---------- Aardman ----------
    { q: "What is Wallace's favourite food in Wallace & Gromit?", a: "Cheese", wrong: ["Fish fingers", "Jelly", "Chocolate", "Spaghetti"], level: 1, emoji: "🫖",
      fact: "His favourite kind is Wensleydale, a crumbly cheese from Yorkshire." },
    { q: "In The Wrong Trousers, what animal is the sneaky Feathers McGraw?", a: "A penguin", wrong: ["A puffin", "A duck", "A crow", "An owl"], level: 2, emoji: "💎",
      fact: "He disguises himself as a chicken by wearing a red rubber glove on his head!" },
    { q: "In which Wallace & Gromit film did Shaun the Sheep first appear?", a: "A Close Shave", wrong: ["The Wrong Trousers", "A Grand Day Out", "The Curse of the Were-Rabbit"], level: 3, emoji: "🐑",
      fact: "Shaun was such a hit that he got his own TV series in 2007, and later his own films." },

    // ---------- Studio Ghibli ----------
    { q: "In My Neighbour Totoro, what magical bus do the girls ride?", a: "A Catbus", wrong: ["A Dogbus", "A Frogbus", "A Snailbus"], level: 2, emoji: "🌳",
      fact: "Totoro became the logo of Studio Ghibli, the Japanese studio that made the film." },
    { q: "In Kiki's Delivery Service, what is the name of Kiki's black cat?", a: "Jiji", wrong: ["Lily", "Luna", "Totoro", "Salem"], level: 3, emoji: "🧹",
      fact: "Kiki is a young witch who must leave home at 13 and live in a new town for a whole year." },
    { q: "In Ponyo, what does Sosuke think Ponyo is when he finds her stuck in a jar?", a: "A goldfish", wrong: ["A jellyfish", "A crab", "A seal", "A starfish"], level: 2, emoji: "🌊",
      fact: "Ponyo's father calls her Brunhilde. It's Sosuke who gives her the name Ponyo." },

    // ---------- More Disney, LEGO, Spider-Verse ----------
    { q: "In Lilo & Stitch, what is Stitch's experiment number?", a: "626", wrong: ["101", "123", "404", "999"], level: 2, emoji: "🌺",
      fact: "Stitch was made by an alien scientist called Jumba. Lilo lives on the Hawaiian island of Kauai and teaches him that 'ohana' means family." },
    { q: "In Tangled, what kind of animal is Rapunzel's little friend Pascal?", a: "A chameleon", wrong: ["A frog", "A mouse", "A tortoise", "A parrot"], level: 1, emoji: "🏰",
      fact: "The palace horse, Maximus, acts more like a sniffer dog, tracking Flynn Rider by his scent wherever he goes!" },
    { q: "In The LEGO Movie, what is the name of the ordinary builder who becomes a hero?", a: "Emmet", wrong: ["Benny", "Unikitty", "Lord Business", "Metalbeard"], level: 2, emoji: "🧱",
      fact: "The film looks like stop-motion, but it was made on computers using virtual copies of real LEGO bricks." },
    { q: "In Spider-Man: Into the Spider-Verse, which Brooklyn teenager becomes the new Spider-Man?", a: "Miles Morales", wrong: ["Peter Parker", "Gwen Stacy", "Peter Porker", "Peni Parker"], level: 2, emoji: "🕸️",
      fact: "One of the other Spider-heroes is Spider-Ham, a cartoon pig whose real name is Peter Porker." },

    // ---------- More Pixar ----------
    { q: "In Toy Story 3, what is the daycare the toys are sent to called?", a: "Sunnyside", wrong: ["Happy Days", "Rainbow Room", "Little Stars", "Sunflower Hall"], level: 2, emoji: "🧸",
      fact: "In Toy Story 3, Andy is 17 and packing up his room to go to college." },
    { q: "In Toy Story 4, what does Bonnie make her new toy friend out of?", a: "A plastic spork", wrong: ["A wooden spoon", "A paper cup", "A cardboard box", "An old sock"], level: 1, emoji: "🍴",
      fact: "The new toy, Forky, keeps trying to jump into the bin, because he thinks he's rubbish!" },
    { q: "In Finding Nemo, which city is Nemo taken to, to live in a dentist's fish tank?", a: "Sydney", wrong: ["Melbourne", "Perth", "Brisbane", "Auckland"], level: 2, emoji: "🦷",
      fact: "Dory remembers the address from a diver's mask: P. Sherman, 42 Wallaby Way, Sydney." },
    { q: "In The Incredibles, what is Dash's superpower?", a: "Super speed", wrong: ["Turning invisible", "Super stretching", "Freezing things", "Flying"], level: 1, emoji: "💨",
      fact: "Dash can run so fast that he even races across the top of the water!" },
    { q: "In Ratatouille, how does Remy steer Linguini while he cooks?", a: "By tugging his hair", wrong: ["By whistling", "By tapping his foot", "By writing notes", "By ringing a bell"], level: 2, emoji: "🐀",
      fact: "Remy hides under Linguini's chef's hat. In real life, rats have a brilliant sense of smell, just like Remy." },
    { q: "In Up, what lets Dug the dog talk?", a: "A special collar", wrong: ["A magic bone", "A tiny radio", "A wizard's spell", "A golden bell"], level: 2, emoji: "🐶",
      fact: "Dug is so easily distracted that he stops mid-sentence whenever he thinks he's seen a squirrel!" },
    { q: "In Cars, what is the little desert town where Lightning McQueen gets stuck?", a: "Radiator Springs", wrong: ["Rusty Gulch", "Tailpipe Town", "Gasket Junction", "Dusty Valley"], level: 2, emoji: "🌵",
      fact: "The town was forgotten when a big new motorway was built and the traffic stopped driving through." },
    { q: "In Inside Out, what does Riley's imaginary friend Bing Bong cry?", a: "Sweets", wrong: ["Bubbles", "Glitter", "Marbles", "Raindrops"], level: 3, emoji: "🍬",
      fact: "Bing Bong is made of candyfloss, and he's part cat, part elephant and part dolphin." },
    { q: "In Luca, what do Luca and Alberto dream of riding?", a: "A Vespa scooter", wrong: ["A racing car", "A hot-air balloon", "A speedboat", "A horse"], level: 2, emoji: "🛵",
      fact: "Vespa is a real Italian scooter, and its name means 'wasp' in Italian." },

    // ---------- More Disney ----------
    { q: "In Frozen, what kind of animal is Sven?", a: "A reindeer", wrong: ["A moose", "A horse", "A goat", "A wolf"], level: 1, emoji: "🦌",
      fact: "Sven loves carrots so much that he'll happily share one, even after someone else has taken a bite!" },
    { q: "In Moana, what is the name of Moana's home island?", a: "Motunui", wrong: ["Te Fiti", "Lalotai", "Matangi", "Puanani"], level: 3, emoji: "🏝️",
      fact: "'Moana' means 'ocean' or 'sea' in Hawaiian, Māori and other Polynesian languages." },
    { q: "In Encanto, what is Luisa's magic gift?", a: "Super strength", wrong: ["Super hearing", "Making flowers grow", "Changing her face", "Talking to animals"], level: 1, emoji: "💪",
      fact: "Each Madrigal has their own gift. Little cousin Antonio's gift is talking to animals." },
    { q: "In Zootopia (Zootropolis), what kind of animal is the mayor's helper, Bellwether?", a: "A sheep", wrong: ["A goat", "A rabbit", "A mouse", "A llama"], level: 3, emoji: "🐑",
      fact: "In real life, a bellwether is a sheep that leads the flock, wearing a bell round its neck." },
    { q: "In Aladdin, how many wishes does the Genie grant?", a: "Three", wrong: ["One", "Two", "Five", "Ten"], level: 1, emoji: "🪔",
      fact: "Aladdin uses his very last wish to set the Genie free." },
    { q: "In Beauty and the Beast, which flower shows how long the spell has left?", a: "A rose", wrong: ["A lily", "A tulip", "A daisy", "A sunflower"], level: 1, emoji: "🌹",
      fact: "The magic rose is kept under a glass dome in the Beast's forbidden West Wing." },
    { q: "In The Lion King, what is the name of the young lion's wicked uncle?", a: "Scar", wrong: ["Mufasa", "Rafiki", "Banzai", "Zazu"], level: 1, emoji: "🦁",
      fact: "James Earl Jones voiced the wise king Mufasa in both the 1994 film and the 2019 remake." },
    { q: "In The Little Mermaid, what does Ariel give the sea witch to get legs?", a: "Her voice", wrong: ["Her tail", "Her hair", "Her crown", "Her seashells"], level: 1, emoji: "🐚",
      fact: "Hans Christian Andersen wrote the first Little Mermaid story in Denmark in 1837." },
    { q: "In Mary Poppins, what does Mary Poppins use to float down from the sky?", a: "Her umbrella", wrong: ["A kite", "A hot-air balloon", "A broomstick", "A magic carpet"], level: 1, emoji: "☂️",
      fact: "Her carpet bag looks empty, but she pulls out a hat stand, a mirror, a lamp and a plant!" },
    { q: "In Pinocchio, what happens to Pinocchio's nose when he tells a lie?", a: "It grows longer", wrong: ["It turns red", "It falls off", "It starts to glow", "It sneezes"], level: 1, emoji: "🤥",
      fact: "Pinocchio was first a story by Carlo Collodi, written in Italy in the 1880s." },
    { q: "In Dumbo, what lets the little elephant fly?", a: "His enormous ears", wrong: ["A magic hat", "A circus cannon", "A bunch of balloons", "His long trunk"], level: 1, emoji: "🐘",
      fact: "Dumbo's real name is Jumbo Junior. 'Dumbo' is an unkind nickname, but he turns it into a famous one!" },
    { q: "In Big Hero 6, what is Baymax built to do?", a: "Look after people's health", wrong: ["Fight crime", "Cook dinner", "Build houses", "Play football"], level: 2, emoji: "🩹",
      fact: "Baymax is inflatable, so he's soft and squishy, and he has to keep away from sharp things!" },
    { q: "In Bolt, what does the dog Bolt wrongly believe?", a: "That he has superpowers", wrong: ["That he's a cat", "That he can talk", "That he's a wolf", "That he's a robot"], level: 2, emoji: "⚡",
      fact: "Bolt is the star of a TV show, and nobody has told him that his powers are just special effects." },
    { q: "In The Wizard of Oz, what colour is the road Dorothy follows?", a: "Yellow", wrong: ["Red", "Green", "Blue", "Pink"], level: 1, emoji: "🧱",
      fact: "In the 1939 film Dorothy's magic slippers are ruby red, but in the book they're silver!" },

    // ---------- More DreamWorks, Illumination, Aardman and Ghibli ----------
    { q: "In Despicable Me, what does Gru plan to steal?", a: "The Moon", wrong: ["The Eiffel Tower", "The Sun", "A volcano", "The Statue of Liberty"], level: 2, emoji: "🌙",
      fact: "He uses a shrink ray to make it small enough to hold in his hand." },
    { q: "What colour are most Minions?", a: "Yellow", wrong: ["Green", "Blue", "Orange", "Pink"], level: 1, emoji: "🍌",
      fact: "In the Minions film, they've been looking for a boss to follow ever since the time of the dinosaurs." },
    { q: "In Kung Fu Panda, what kind of animal is Master Shifu?", a: "A red panda", wrong: ["A raccoon", "A fox", "A lemur", "A cat"], level: 3, emoji: "🥋",
      fact: "Real red pandas live in mountain forests in the Himalayas and China, and are only about the size of a big cat." },
    { q: "In How to Train Your Dragon, what is Hiccup's dad called?", a: "Stoick", wrong: ["Gobber", "Snotlout", "Fishlegs", "Ruffnut"], level: 3, emoji: "🐉",
      fact: "Hiccup builds Toothless a new tail fin, so the two of them can fly together." },
    { q: "In Madagascar, which zoo do the animals come from?", a: "Central Park Zoo", wrong: ["London Zoo", "San Diego Zoo", "Bronx Zoo", "Berlin Zoo"], level: 3, emoji: "🦓",
      fact: "The real Central Park Zoo is in New York City, right in the middle of Manhattan." },
    { q: "In Ice Age, what is Scrat the squirrel always chasing?", a: "An acorn", wrong: ["A walnut", "A pine cone", "A berry", "A banana"], level: 1, emoji: "🌰",
      fact: "Scrat is a made-up 'sabre-toothed squirrel', and he never says a word, he just squeaks!" },
    { q: "In A Grand Day Out, where do Wallace and Gromit fly to find cheese?", a: "The Moon", wrong: ["Mars", "Iceland", "The North Pole", "Switzerland"], level: 2, emoji: "🚀",
      fact: "They build a rocket in the basement, because they've run out of cheese for their crackers." },
    { q: "In My Neighbour Totoro, what do the girls lend Totoro at the bus stop?", a: "An umbrella", wrong: ["A scarf", "A lantern", "A blanket", "A hat"], level: 2, emoji: "☂️",
      fact: "Totoro loves the sound of raindrops plopping on his new umbrella." },
  ],
});

export const games = bankTopic({
  id: "games",
  title: "Games, Toys & TV",
  emoji: "🎮",
  eyebrow: "Games, Toys & TV",
  guide: { who: "rufus", place: "Game night" },
  questions: [
    // ---------- Nintendo ----------
    { q: "What colour is Luigi's cap in the Mario games?", a: "Green", wrong: ["Red", "Blue", "Yellow", "Purple"], level: 1, emoji: "🍄",
      fact: "Luigi is Mario's younger twin brother, and in lots of games he can jump higher than Mario." },
    { q: "What kind of creature is Yoshi?", a: "A dinosaur", wrong: ["A penguin", "A frog", "A horse", "A caterpillar"], level: 1, emoji: "🍄",
      fact: "Yoshi first appeared in Super Mario World in 1990, where Mario could ride on his back." },
    { q: "Who rules the Mushroom Kingdom in the Mario games?", a: "Princess Peach", wrong: ["Princess Daisy", "Rosalina", "Pauline", "Toadette"], level: 1, emoji: "👑",
      fact: "In the first Mario games sold in America, she was called Princess Toadstool." },
    { q: "Which spiky-shelled king keeps causing trouble for Mario?", a: "Bowser", wrong: ["Wario", "King Boo", "Kamek", "Donkey Kong"], level: 1, emoji: "🏰",
      fact: "In Japan, Bowser is called Koopa, and he has a mischief-making son called Bowser Jr." },
    { q: "In the first Donkey Kong arcade game, what was Mario called?", a: "Jumpman", wrong: ["Hopman", "Plumber Pete", "Captain Jump", "Super Joe"], level: 3, emoji: "🕹️",
      fact: "Back then Mario was a carpenter, not a plumber. He became a plumber in Mario Bros. in 1983." },
    { q: "What is the name of Kirby's home in the Kirby games?", a: "Dream Land", wrong: ["Hyrule", "Green Hill", "Sarasaland", "Mushroom Kingdom"], level: 3, emoji: "⭐",
      fact: "On the American box of his very first game, Kirby's Dream Land, Kirby was shown white instead of pink!" },
    { q: "What kind of animal is Donkey Kong?", a: "A gorilla", wrong: ["A donkey", "A bear", "An orangutan", "A lion"], level: 1, emoji: "🍌",
      fact: "His creator, Shigeru Miyamoto, is said to have picked the name because he thought 'donkey' meant silly or stubborn." },
    { q: "In Animal Crossing, what kind of animal is Tom Nook?", a: "A raccoon dog", wrong: ["A red fox", "A brown bear", "A squirrel", "A beaver"], level: 2, emoji: "🏝️",
      fact: "In English he's often called a raccoon, but he's a tanuki, or raccoon dog: a real East Asian animal from the dog family." },
    { q: "In The Legend of Zelda games, what is the hero in the green tunic called?", a: "Link", wrong: ["Zelda", "Ganon", "Epona", "Navi"], level: 2, emoji: "🎮",
      fact: "Lots of people mix them up: the games are named after Princess Zelda, but the hero is usually Link." },
    { q: "What is the name of the kingdom in most Zelda games?", a: "Hyrule", wrong: ["Termina", "Koholint", "Dream Land", "Arendelle"], level: 3, emoji: "🏰",
      fact: "Princess Zelda was named after Zelda Fitzgerald, an American writer. Shigeru Miyamoto just liked the sound of her name." },

    // ---------- Pokémon ----------
    { q: "What type of Pokémon is Pikachu?", a: "Electric", wrong: ["Fire", "Water", "Grass", "Psychic"], level: 1, emoji: "🎒",
      fact: "Its name mixes two Japanese sounds: 'pika' for a sparkle of electricity and 'chu' for a mouse's squeak." },
    { q: "What does Charmander evolve into?", a: "Charmeleon", wrong: ["Wartortle", "Ivysaur", "Raichu", "Ninetales"], level: 2, emoji: "✨",
      fact: "Charmeleon then evolves into Charizard, which is a Fire and Flying type." },
    { q: "Which Pokémon can evolve into Vaporeon, Jolteon or Flareon?", a: "Eevee", wrong: ["Pikachu", "Bulbasaur", "Jigglypuff", "Snorlax"], level: 2, emoji: "✨",
      fact: "So far Eevee has eight different evolutions, more than any other Pokémon! Fans call them Eeveelutions." },
    { q: "In Pokémon, which type is strong against Fire types?", a: "Water", wrong: ["Grass", "Bug", "Ice", "Steel"], level: 2, emoji: "🔥",
      fact: "Fire beats Grass, Grass beats Water and Water beats Fire, a bit like rock, paper, scissors." },
    { q: "Which Pokémon is number 1 in the National Pokédex?", a: "Bulbasaur", wrong: ["Pikachu", "Mew", "Charmander", "Squirtle"], level: 3, emoji: "📖",
      fact: "Pikachu is number 25, and Mew was number 151, the last one in the very first games." },

    // ---------- Minecraft ----------
    { q: "Which Minecraft mob began as a mistake when Notch was making a pig?", a: "The Creeper", wrong: ["The Enderman", "The Slime", "The Ghast", "The Iron Golem"], level: 3, emoji: "🐷",
      fact: "Creepers are scared of cats and ocelots, so a pet cat keeps them away!" },
    { q: "In Minecraft, what do you need to make a crafting table?", a: "4 wooden planks", wrong: ["4 cobblestones", "2 sticks", "1 iron ingot", "8 wool"], level: 1, emoji: "⛏️",
      fact: "A crafting table gives you a 3×3 crafting grid, bigger than the 2×2 grid in your inventory." },
    { q: "In Minecraft, which block do you build a Nether portal frame from?", a: "Obsidian", wrong: ["Glowstone", "Netherrack", "Bedrock", "Gold blocks"], level: 2, emoji: "🟪",
      fact: "Obsidian forms when water meets a lava source block, and you need a diamond pickaxe or better to mine it." },
    { q: "In Minecraft, which biome do pandas live in?", a: "Jungle", wrong: ["Desert", "Snowy plains", "Mushroom fields", "Badlands"], level: 2, emoji: "🐼",
      fact: "Minecraft pandas have personalities: some are lazy, some playful, and some worried." },

    // ---------- Sonic ----------
    { q: "What kind of animal is Sonic?", a: "A hedgehog", wrong: ["A fox", "An echidna", "A porcupine", "An armadillo"], level: 1, emoji: "💨",
      fact: "His best friend Tails is a two-tailed fox who can fly by spinning his tails like a helicopter." },
    { q: "What does Sonic collect as he races through each level?", a: "Gold rings", wrong: ["Gold coins", "Bananas", "Mushrooms", "Feathers"], level: 1, emoji: "💨",
      fact: "Sonic was made blue to match the colour of SEGA's logo." },

    // ---------- Toys ----------
    { q: "Which country does LEGO come from?", a: "Denmark", wrong: ["Sweden", "Germany", "Norway", "Switzerland"], level: 2, emoji: "🧱",
      fact: "LEGO began in 1932 in a carpenter's workshop in Billund, making wooden toys. The plastic bricks came later." },
    { q: "What does the name LEGO mean?", a: "Play well", wrong: ["Build big", "Little bricks", "Stack it up", "Clever hands"], level: 3, emoji: "🧱",
      fact: "It comes from the Danish words 'leg godt'. By chance, 'lego' is also a Latin word that can mean 'I gather'!" },
    { q: "How many colours does a classic Rubik's Cube have?", a: "6", wrong: ["4", "8", "9", "12"], level: 1, emoji: "🧩",
      fact: "There are over 43 quintillion ways to mix up a Rubik's Cube, but only one way is solved!" },
    { q: "In which country was the Rubik's Cube invented?", a: "Hungary", wrong: ["Japan", "Russia", "USA", "Poland"], level: 3, emoji: "🧩",
      fact: "Ernő Rubik, a Hungarian architecture teacher, made the first one in 1974. At first it was called the Magic Cube." },
    { q: "Before it became a toy, what was Play-Doh sold as?", a: "Wallpaper cleaner", wrong: ["Bread dough", "Chewing gum", "Shoe polish", "Glue"], level: 3, emoji: "🎨",
      fact: "When homes stopped needing wallpaper cleaner, a nursery teacher used it for crafts, and it became a toy in 1956." },

    // ---------- Chess and board games ----------
    { q: "In chess, which piece moves in an L shape?", a: "The knight", wrong: ["The bishop", "The rook", "The queen", "The king"], level: 1, emoji: "♟️",
      fact: "The knight is the only piece that can jump over other pieces in a normal move." },
    { q: "How many squares are on a chessboard?", a: "64", wrong: ["36", "49", "81", "100"], level: 2, emoji: "♟️",
      fact: "That's 8 rows of 8 squares, and each player starts the game with 16 pieces." },
    { q: "In chess, what is the special move where the king and a rook move together?", a: "Castling", wrong: ["En passant", "Checkmate", "Promotion", "Stalemate"], level: 3, emoji: "👑",
      fact: "Castling is the only move in chess where you move two of your own pieces in one turn." },
    { q: "In classic Monopoly, how much money do you collect for passing GO?", a: "200", wrong: ["50", "100", "500", "1,000"], level: 2, emoji: "💰",
      fact: "The classic American board uses street names from Atlantic City, and the UK board uses places in London." },
    { q: "Which game has you pull wooden blocks from a tower without knocking it over?", a: "Jenga", wrong: ["Kerplunk", "Buckaroo!", "Operation", "Mouse Trap"], level: 1, emoji: "🪵",
      fact: "The name comes from 'kujenga', a Swahili word meaning 'to build'." },
    { q: "In Scrabble, how many letter tiles does each player keep on their rack?", a: "7", wrong: ["5", "6", "8", "10"], level: 3, emoji: "🔤",
      fact: "Using all seven tiles in one turn earns you 50 bonus points!" },

    // ---------- TV cartoons ----------
    { q: "What breed of dog is Bluey?", a: "Blue Heeler", wrong: ["Border Collie", "Labrador", "Dalmatian", "Beagle"], level: 2, emoji: "🐶",
      fact: "Her little sister Bingo is a Red Heeler: the same breed (Australian Cattle Dog) in a different colour." },
    { q: "In which country is Bluey set?", a: "Australia", wrong: ["New Zealand", "England", "Canada", "Ireland"], level: 1, emoji: "📺",
      fact: "Bluey's family lives in Brisbane, in a wooden house on stilts called a Queenslander." },
    { q: "What is the name of Bluey's dad?", a: "Bandit", wrong: ["Rad", "Stripe", "Bob", "Chilli"], level: 2, emoji: "📺",
      fact: "Bandit is an archaeologist, and Bluey's mum, Chilli, works in airport security." },
    { q: "Where does SpongeBob SquarePants live?", a: "In a pineapple", wrong: ["Under a rock", "In an Easter Island head", "In a treedome", "In an anchor"], level: 1, emoji: "🧽",
      fact: "SpongeBob's creator, Stephen Hillenburg, taught marine biology before he became a cartoonist." },
    { q: "What is the name of SpongeBob's pet snail?", a: "Gary", wrong: ["Larry", "Patrick", "Plankton", "Squidward"], level: 2, emoji: "🧽",
      fact: "Gary is a sea snail, but he meows just like a cat!" },
    { q: "What is the name of Peppa Pig's little brother?", a: "George", wrong: ["Richard", "Danny", "Pedro", "Freddy"], level: 1, emoji: "🐷",
      fact: "George's favourite toy is his dinosaur, called Mr. Dinosaur." },
    { q: "In PAW Patrol, what is the name of the boy who leads the pups?", a: "Ryder", wrong: ["Chase", "Rocky", "Marshall", "Rubble"], level: 1, emoji: "🐾",
      fact: "The pups work out of a tall tower called the Lookout, in a town called Adventure Bay." },
    { q: "In PAW Patrol, what breed of dog is Chase?", a: "German Shepherd", wrong: ["Dalmatian", "Bulldog", "Cockapoo", "Labrador"], level: 2, emoji: "🐾",
      fact: "Marshall is the Dalmatian, Rubble the bulldog, Skye the cockapoo and Zuma the Labrador." },
    { q: "What breed of dog is Scooby-Doo?", a: "Great Dane", wrong: ["Beagle", "Bulldog", "Poodle", "Boxer"], level: 2, emoji: "🔍",
      fact: "Scooby-Doo first appeared on TV in 1969, in a show called Scooby-Doo, Where Are You!" },
    { q: "In Scooby-Doo, what is the name of the gang's van?", a: "The Mystery Machine", wrong: ["The Ghost Bus", "The Clue Cruiser", "The Spooky Van", "The Snack Wagon"], level: 2, emoji: "🔍",
      fact: "The gang call themselves Mystery Inc.: Fred, Daphne, Velma, Shaggy and Scooby." },
    { q: "What colour are the Smurfs?", a: "Blue", wrong: ["Green", "Red", "Yellow", "Orange"], level: 1, emoji: "🍄",
      fact: "The Smurfs were created in Belgium by an artist called Peyo in 1958. In French they're called Schtroumpfs!" },

    // ---------- More games ----------
    { q: "In Mario games, what makes Mario grow super big?", a: "A Super Mushroom", wrong: ["A Fire Flower", "A Super Star", "A Super Leaf", "A golden coin"], level: 1, emoji: "🍄",
      fact: "A green 1-Up Mushroom is different: it gives you an extra life." },
    { q: "In Mario Kart, which item zooms after the racer in first place?", a: "The Spiny Shell", wrong: ["The Green Shell", "The Banana", "The Mushroom", "The Star"], level: 2, emoji: "🏎️",
      fact: "Lots of players call it the Blue Shell. It first appeared in Mario Kart 64." },
    { q: "What can Kirby do after swallowing an enemy?", a: "Copy its power", wrong: ["Turn invisible", "Grow giant", "Change colour", "Teleport home"], level: 2, emoji: "⭐",
      fact: "Kirby can also puff himself up with air and float through the sky." },
    { q: "What two colours is a classic Poké Ball?", a: "Red and white", wrong: ["Blue and yellow", "Green and black", "Purple and pink", "Orange and grey"], level: 1, emoji: "⚪",
      fact: "Pokémon began in Japan in 1996, with two games called Pocket Monsters Red and Green." },
    { q: "Which huge Pokémon is famous for blocking paths by falling asleep?", a: "Snorlax", wrong: ["Jigglypuff", "Psyduck", "Bulbasaur", "Squirtle"], level: 2, emoji: "😴",
      fact: "Snorlax weighs 460 kilograms, about as much as six grown-ups put together!" },
    { q: "In Minecraft, what is the weakest pickaxe that can mine diamonds?", a: "Iron", wrong: ["Stone", "Wooden", "Golden"], level: 2, emoji: "💎",
      fact: "Golden tools work very fast, but they wear out quicker than any other kind." },
    { q: "Which Minecraft mob gets upset if you look it right in the eyes?", a: "The Enderman", wrong: ["The Creeper", "The Zombie", "The Skeleton", "The Spider"], level: 2, emoji: "👀",
      fact: "Endermen can pick up some blocks and carry them about, and they hate water." },
    { q: "In Minecraft, what do you give a wolf to tame it?", a: "Bones", wrong: ["Raw fish", "Wheat", "Carrots", "Seeds"], level: 2, emoji: "🐺",
      fact: "A tamed wolf gets a red collar, and you can dye the collar any colour you like." },
    { q: "In the Sonic games, what colour is Knuckles?", a: "Red", wrong: ["Blue", "Yellow", "Green", "Purple"], level: 2, emoji: "💎",
      fact: "Knuckles is an echidna who guards the giant Master Emerald on Angel Island." },
    { q: "In Animal Crossing, what is the money called?", a: "Bells", wrong: ["Coins", "Leaves", "Stars", "Shells"], level: 2, emoji: "🔔",
      fact: "In New Horizons you can also earn Nook Miles by doing little jobs around your island." },
    { q: "In Splatoon, what do players cover the ground with to win a Turf War?", a: "Ink", wrong: ["Slime", "Glitter", "Bubbles", "Sand"], level: 2, emoji: "🦑",
      fact: "The players are Inklings, who can turn into squid and swim through their own colour." },
    { q: "What does Pac-Man eat so he can chase the ghosts?", a: "Power pellets", wrong: ["Cherries", "Gold coins", "Mushrooms", "Stars"], level: 2, emoji: "🟡",
      fact: "Pac-Man's creator, Toru Iwatani, is said to have got the idea from a pizza with one slice missing." },

    // ---------- More toys and games ----------
    { q: "What are the little LEGO people called?", a: "Minifigures", wrong: ["Brickies", "Legoids", "Blockheads", "Tiny Builders"], level: 1, emoji: "🧱",
      fact: "The LEGO minifigure first appeared in 1978, with a big smile and no nose." },
    { q: "Which toy is a spring that can walk down the stairs by itself?", a: "A Slinky", wrong: ["A yo-yo", "A spinning top", "A jack-in-the-box", "A pogo stick"], level: 1, emoji: "🌀",
      fact: "An engineer called Richard James got the idea in 1943 when a spring fell off a shelf and kept on going." },
    { q: "In Snakes and Ladders, what happens when you land at the bottom of a ladder?", a: "You climb up it", wrong: ["You miss a go", "You go back to start", "You slide down", "You roll again"], level: 1, emoji: "🪜",
      fact: "The game comes from India, where it was called Moksha Patam and taught children about good and bad deeds." },
    { q: "What does 'uno' mean in Spanish?", a: "One", wrong: ["Win", "Card", "Go", "Stop"], level: 1, emoji: "🃏",
      fact: "In the card game UNO, if you forget to shout 'UNO!' with one card left, you must pick up two cards." },
    { q: "In draughts (checkers), what happens when a piece reaches the far side of the board?", a: "It becomes a king", wrong: ["It's taken off", "It goes back to start", "It wins the game", "It swaps sides"], level: 2, emoji: "⚫",
      fact: "To make a king you stack a second piece on top, and then it can move backwards too." },

    // ---------- More TV ----------
    { q: "In Bluey, which game is all about keeping a balloon off the floor?", a: "Keepy Uppy", wrong: ["Magic Xylophone", "Shadowlands", "Hotel", "Featherwand"], level: 2, emoji: "🎈",
      fact: "Most Bluey episodes are only about seven minutes long." },
    { q: "What does Peppa Pig love jumping in?", a: "Muddy puddles", wrong: ["Piles of leaves", "Bouncy castles", "Big haystacks", "Snowdrifts"], level: 1, emoji: "💦",
      fact: "Peppa Pig first came to TV in the UK in 2004." },
    { q: "Where does SpongeBob work?", a: "The Krusty Krab", wrong: ["The Chum Bucket", "Goofy Goober's", "Mrs. Puff's school", "Weenie Hut Jr's"], level: 1, emoji: "🍔",
      fact: "SpongeBob is a fry cook who flips Krabby Patties, and he LOVES his job." },
    { q: "What number is painted on Thomas the Tank Engine?", a: "1", wrong: ["2", "4", "7", "10"], level: 2, emoji: "🚂",
      fact: "Thomas first chugged into a book in 1946, in the Railway Series stories by the Reverend W. Awdry." },

    // ---------- Sport ----------
    { q: "In basketball, how many points do you get for a basket from outside the big arc?", a: "3", wrong: ["1", "2", "4", "5"], level: 2, emoji: "🏀",
      fact: "Basketball was invented in 1891 by James Naismith, using peach baskets as hoops!" },
    { q: "How many players does a football (soccer) team have on the pitch at kick-off?", a: "11", wrong: ["9", "10", "12", "15"], level: 1, emoji: "⚽",
      fact: "One of them is the goalkeeper, the only player who can touch the ball with their hands in play, and only in their own penalty area." },
    { q: "How many rings are on the Olympic flag?", a: "5", wrong: ["3", "4", "6", "7"], level: 1, emoji: "🏅",
      fact: "The rings were designed in 1913 by Pierre de Coubertin, who started the modern Olympic Games." },
    { q: "In tennis, what is a score of zero called?", a: "Love", wrong: ["Nil", "Duck", "Blank"], level: 3, emoji: "🎾",
      fact: "Nobody is completely sure why. One idea is that it comes from 'l'œuf', French for 'egg', because 0 looks like an egg." },
  ],
});
