// 🚀 SPACE EXPLORER - a "question bank" topic.
// This is the simplest kind of topic: just write questions in a list!
// level: 1 = easy, 2 = medium, 3 = hard.

import { bankTopic } from "../kit.js";

export default bankTopic({
  id: "space",
  title: "Space Explorer",
  emoji: "🚀",
  color: "#8b5cf6",
  blurb: "Planets, stars and astronauts.",
  eyebrow: "Space quiz",
  orbit: ["🪐", "🌍", "🌕", "☀️", "☄️", "🚀", "🛰️", "⭐"], // these circle around Rufus
  music: "cosmic",                                        // which song plays (see sound.js)
  questions: [
    { q: "Which planet is closest to the Sun?", a: "Mercury", wrong: ["Venus", "Mars", "Earth"], level: 1, emoji: "☀️",
      fact: "A year on Mercury lasts only 88 Earth days." },
    { q: "Which is the biggest planet in our solar system?", a: "Jupiter", wrong: ["Saturn", "Neptune", "Earth"], level: 1, emoji: "🪐",
      fact: "More than 1,000 Earths could fit inside Jupiter." },
    { q: "Which planet is called the Red Planet?", a: "Mars", wrong: ["Venus", "Jupiter", "Mercury"], level: 1, emoji: "🔴",
      fact: "Mars looks red because its dusty ground is full of rusty iron." },
    { q: "Which planet has the most famous rings?", a: "Saturn", wrong: ["Jupiter", "Mars", "Venus"], level: 1, emoji: "🪐",
      fact: "Saturn's rings are made of chunks of ice and rock." },
    { q: "What is the Sun?", a: "A star", wrong: ["A planet", "A moon", "A comet"], level: 1, emoji: "☀️",
      fact: "The Sun is the closest star to Earth." },
    { q: "How many planets are in our solar system?", a: "8", wrong: ["7", "9", "10"], level: 1, emoji: "🔭",
      fact: "Pluto used to be called the ninth planet, but in 2006 it became a dwarf planet." },
    { q: "What is the name of our galaxy?", a: "The Milky Way", wrong: ["Andromeda", "The Whirlpool", "The Sombrero"], level: 1, emoji: "🌌",
      fact: "On a very dark night you can see the Milky Way as a glowing band across the sky." },
    { q: "About how long does Earth take to go around the Sun?", a: "365 days", wrong: ["24 hours", "30 days", "100 days"], level: 1, emoji: "🌍",
      fact: "That's one year! Every 4 years we add a leap day to keep calendars on track." },
    { q: "About how long does Earth take to spin around once?", a: "24 hours", wrong: ["1 hour", "7 days", "365 days"], level: 1, emoji: "🌍",
      fact: "One spin of the Earth gives us one day and one night." },
    { q: "What force pulls things down toward the Earth?", a: "Gravity", wrong: ["Magnetism", "Wind", "Sunlight"], level: 1, emoji: "🍎",
      fact: "Gravity also keeps the Moon going around the Earth." },
    { q: "Which used-to-be planet is now called a dwarf planet?", a: "Pluto", wrong: ["Mercury", "Mars", "Neptune"], level: 1, emoji: "🧊",
      fact: "Pluto is smaller than our own Moon." },
    { q: "Who was the first person to walk on the Moon?", a: "Neil Armstrong", wrong: ["Buzz Aldrin", "Yuri Gagarin", "Sally Ride"], level: 2, emoji: "👨‍🚀",
      fact: "Neil Armstrong stepped onto the Moon on July 20, 1969." },
    { q: "Who was the first human to travel into space?", a: "Yuri Gagarin", wrong: ["Neil Armstrong", "John Glenn", "Alan Shepard"], level: 2, emoji: "🚀",
      fact: "Yuri Gagarin flew all the way around the Earth in 1961." },
    { q: "Which is the hottest planet?", a: "Venus", wrong: ["Mercury", "Mars", "Jupiter"], level: 2, emoji: "🔥",
      fact: "Venus's thick clouds trap heat, so it's even hotter than Mercury." },
    { q: "Which planet has the Great Red Spot?", a: "Jupiter", wrong: ["Saturn", "Mars", "Neptune"], level: 2, emoji: "🌀",
      fact: "The Great Red Spot is a giant storm that is bigger than the whole Earth." },
    { q: "What do we call a scientist who studies stars and planets?", a: "An astronomer", wrong: ["An astrologer", "A geologist", "A biologist"], level: 2, emoji: "🔭",
      fact: "Astronomers use telescopes to see things trillions of miles away." },
    { q: "Where do astronauts live while they orbit the Earth?", a: "The International Space Station", wrong: ["The Hubble Telescope", "Voyager 1", "The Moon base"], level: 2, emoji: "🛰️",
      fact: "The space station zooms around the Earth about 16 times every day." },
    { q: "Which planet is farthest from the Sun?", a: "Neptune", wrong: ["Uranus", "Saturn", "Pluto"], level: 2, emoji: "🔵",
      fact: "Neptune takes about 165 Earth years to go around the Sun once." },
    { q: "Where does moonlight come from?", a: "Sunlight bouncing off the Moon", wrong: ["Fire on the Moon", "Lights from Earth", "Glowing Moon rocks"], level: 2, emoji: "🌕",
      fact: "The Moon doesn't make its own light. It's like a giant mirror for the Sun." },
    { q: "What is a shooting star really?", a: "A space rock burning up in our sky", wrong: ["A star falling to Earth", "A planet moving fast", "A blinking satellite"], level: 2, emoji: "🌠",
      fact: "Most shooting stars are smaller than a grain of sand!" },
    { q: "Which is the closest star to Earth?", a: "The Sun", wrong: ["Proxima Centauri", "The North Star", "Sirius"], level: 2, emoji: "⭐",
      fact: "The next closest star, Proxima Centauri, is more than 4 light-years away." },
    { q: "Which mission first landed people on the Moon?", a: "Apollo 11", wrong: ["Apollo 13", "Gemini 4", "Artemis 1"], level: 2, emoji: "🌙",
      fact: "Apollo 11 landed on the Moon in July 1969." },
    { q: "When the Moon looks completely dark, what is it called?", a: "A new moon", wrong: ["A full moon", "A half moon", "A blue moon"], level: 2, emoji: "🌑",
      fact: "During a new moon, the side facing us isn't lit by the Sun." },
    { q: "Which planet spins on its side, like a rolling ball?", a: "Uranus", wrong: ["Neptune", "Saturn", "Mars"], level: 3, emoji: "🎳",
      fact: "Uranus is tipped over so far that it rolls around the Sun." },
    { q: "Which planet has Olympus Mons, the biggest volcano in the solar system?", a: "Mars", wrong: ["Venus", "Earth", "Mercury"], level: 3, emoji: "🌋",
      fact: "Olympus Mons is about two and a half times taller than Mount Everest." },
    { q: "Which planet has the most moons that scientists have found?", a: "Saturn", wrong: ["Jupiter", "Earth", "Mars"], level: 3, emoji: "🌘",
      fact: "Scientists have found more than 270 moons going around Saturn!" },
    { q: "Which NASA rover landed on Mars in 2021?", a: "Perseverance", wrong: ["Curiosity", "Opportunity", "Sojourner"], level: 3, emoji: "🤖",
      fact: "Perseverance brought a little helicopter called Ingenuity with it." },
    { q: "Which planet is often called the Morning Star or Evening Star?", a: "Venus", wrong: ["Mars", "Jupiter", "Mercury"], level: 3, emoji: "✨",
      fact: "Venus is the brightest planet in our night sky." },
    { q: "About how long does sunlight take to reach Earth?", a: "8 minutes", wrong: ["8 seconds", "8 hours", "8 days"], level: 3, emoji: "💡",
      fact: "Light is the fastest thing there is, but the Sun is about 93 million miles away." },
    { q: "Which planet is almost the same size as Earth?", a: "Venus", wrong: ["Mars", "Mercury", "Jupiter"], level: 3, emoji: "👯",
      fact: "Venus is sometimes called Earth's twin, but it's far too hot to live on." },
  ],
});
