// Builds the country data the game uses, from the open-source flag-icons package (MIT).
//
//   npm run build:data
//
// What it does:
//   1. Reads node_modules/flag-icons/country.json
//   2. Keeps the 195 countries (193 UN members + Vatican City + Palestine)
//   3. Fixes a few names/capitals so they read nicely for kids
//   4. Copies each flag SVG to public/f/<secret-ish-name>.svg
//      (the file name does NOT contain the country code, so peeking at the
//       network tab won't give away the answer)
//   5. Writes src/shared/data/countries.js
//
// You only need to run this again if you upgrade flag-icons.

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, copyFileSync, readdirSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const FI = join(root, "node_modules", "flag-icons");
const OUT_FLAGS = join(root, "public", "f");
const OUT_DATA = join(root, "src", "shared", "data", "countries.js");

// Changing this salt renames every flag file (handy if someone memorises them).
const SALT = "rufus-the-fox-loves-flags";

// 193 UN member states + 2 UN observer states (Vatican City, Palestine).
const KEEP = `af al dz ad ao ag ar am au at az bs bh bd bb by be bz bj bt bo ba bw br bn bg bf bi cv kh
cm ca cf td cl cn co km cg cd cr ci hr cu cy cz dk dj dm do ec eg sv gq er ee sz et fj fi fr ga gm ge de gh gr
gd gt gn gw gy ht hn hu is in id ir iq ie il it jm jp jo kz ke ki kp kr kw kg la lv lb ls lr ly li lt lu mg mw
my mv ml mt mh mr mu mx fm md mc mn me ma mz mm na nr np nl nz ni ne ng mk no om pk pw pa pg py pe ph pl pt qa
ro ru rw kn lc vc ws sm st sa sn rs sc sl sg sk si sb so za ss es lk sd sr se ch sy tj tz th tl tg to tt tn tr
tm tv ug ua ae gb us uy uz vu ve vn ye zm zw va ps`.split(/\s+/).filter(Boolean);

// Friendlier names for kids.
const NAME = {
  us: "United States", gb: "United Kingdom", cz: "Czech Republic", tr: "Türkiye (Turkey)",
  va: "Vatican City", ps: "Palestine", fm: "Micronesia", bn: "Brunei", tl: "East Timor",
  ci: "Côte d'Ivoire", cd: "DR Congo", cg: "Republic of the Congo", st: "São Tomé and Príncipe",
  kn: "Saint Kitts and Nevis", vc: "Saint Vincent and the Grenadines",
};

// Capitals: fix spellings, or null = leave this country out of the capitals quiz
// (because the "capital" is disputed, shared, or not really a city).
const CAPITAL = {
  ua: "Kyiv", sz: "Mbabane", lk: null, bo: null, nr: null, il: null, ps: null,
};

function hashName(code) {
  return createHash("sha256").update(SALT + ":" + code).digest("hex").slice(0, 10);
}

const all = JSON.parse(readFileSync(join(FI, "country.json"), "utf8"));
const byCode = new Map(all.map((c) => [c.code, c]));

const missing = KEEP.filter((c) => !byCode.has(c));
if (missing.length) throw new Error("flag-icons is missing: " + missing.join(", "));
if (new Set(KEEP).size !== 195) throw new Error("Expected 195 countries, got " + new Set(KEEP).size);

rmSync(OUT_FLAGS, { recursive: true, force: true });
mkdirSync(OUT_FLAGS, { recursive: true });
mkdirSync(dirname(OUT_DATA), { recursive: true });

const rows = KEEP.map((code) => {
  const c = byCode.get(code);
  const file = hashName(code) + ".svg";
  copyFileSync(join(FI, c.flag_4x3), join(OUT_FLAGS, file));
  let capital = code in CAPITAL ? CAPITAL[code] : c.capital;
  const name = NAME[code] || c.name;
  if (capital && capital === name) capital = null; // "Monaco is the capital of Monaco" is no fun
  return { code, name, capital: capital || null, continent: c.continent, img: "/f/" + file };
}).sort((a, b) => a.name.localeCompare(b.name));

const header = `// AUTO-GENERATED by scripts/build-data.mjs from flag-icons (MIT). Don't edit by hand:
// change the script and run \`npm run build:data\` instead.
`;
writeFileSync(OUT_DATA, header + "export const COUNTRIES = " + JSON.stringify(rows, null, 0).replace(/\},\{/g, "},\n  {") + ";\n");

console.log(`Wrote ${rows.length} countries -> ${OUT_DATA}`);
console.log(`Copied ${readdirSync(OUT_FLAGS).length} flags -> ${OUT_FLAGS}`);
